### ISSUE TITLE
Optional parameters must appear after all required parameters

### ISSUE THREAD

**Issue by nu8** [dotnet/command-line-api#1062]
If I have a program like this:

~~~cs
using System.CommandLine.DragonFruit;
using System;

class Program {
   static void Main(int start, int len = 1, string argument) {
      var s_out = argument.Substring(start, len);
      Console.WriteLine(s_out);
   }
}
~~~

I get this result:

~~~
error CS1737: Optional parameters must appear after all required parameters
~~~

Fair enough, but thats not how its shown here:

https://github.com/dotnet/command-line-api/blob/main/docs/DragonFruit-overview.md#arguments

**Comment by jonsequitur** [comment]
You'll need to change `string argument` to `string argument = null` in your code.

**Comment by nu8** [comment]
@jonsequitur no, then you lose the checks. For example if you do this:

~~~
static void Main(string argument, int start, int len = 1)
~~~

with no argments, you get this:

~~~
Required argument missing for command: substr

Usage:
  substr [options] <argument>

Arguments:
  <argument>

Options:
  --start <start>    start
  --len <len>        len [default: 1]
~~~

but if you do it your way, with no arguments you get this:

~~~
Unhandled exception: System.Reflection.TargetInvocationException: Exception has
been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of
an object.
   at Program.Main(Int32 start, Int32 len, String argument)
~~~

**Comment by jonsequitur** [comment]
What behavior are you expecting? It looks to me like `argument` is required by your command line, so it shouldn't be declared as optional (i.e. `string argument = null`). The C# compiler therefore requires it come before any optional parameters.

But in terms of the command line syntax, this doesn't matter, as the method parameter order is unrelated to the command line order. Options can go in any order relative to one another and relative to arguments, so given this method signature:

```csharp
static void Main(string argument, int start, int len = 1)
```

Any of these should be valid:

```console
> substr hello --start 0 --len 5
> substr --start 0 --len 5 hello
> substr --len 5 hello --start 0 
```

**Comment by nu8** [comment]
Expected behavior would be:

0 arguments - print usage
1,2,3 arguments - do something

which `static void Main(string argument, int start, int len = 1)` does. But with your suggestion:

~~~cs
static void Main(int start, int len = 1, string argument = null)
~~~

you get this behavior:

0 arguments - Unhandled exception
1,2,3 arguments - do something

**Comment by jonsequitur** [comment]
My initial suggestion was to solve the compile error but I realized that might not be the goal for your command-line rules. If you want `argument` to be required, it needs to come before the optional method parameters  (e.g. `static void Main(string argument, int start, int len = 1)`.)

So does this not do what you need?

**Comment by nu8** [comment]
@jonsequitur, I think you have completely misread the purpose of this post.

The original post gives this example:

~~~cs
static void Main(int start, int len = 1, string argument)
~~~

which produces an error. But this page shows the same syntax:

https://github.com/dotnet/command-line-api/blob/main/docs/DragonFruit-overview.md#arguments

Now, this example works properly:

~~~cs
static void Main(string argument, int start, int len = 1)
~~~

but that doesnt address the original issue. The original issue is essentially
this. Either something needs to change in library code, so that this can run
successfully:

~~~cs
static void Main(int start, int len = 1, string argument)
~~~

**Or**, the code here should be corrected:

https://github.com/dotnet/command-line-api/blob/main/docs/DragonFruit-overview.md#arguments

**Comment by jonsequitur** [comment]
The code you're presenting as a problem doesn't appear in the linked docs.

**Comment by nu8** [comment]
The example given is similar to this:

~~~
static void Main(int start, int len = 1, string argument = null)
~~~

which works fine if you provide `argument`. But if you dont, you get this:

~~~
Unhandled exception: System.Reflection.TargetInvocationException: Exception has
been thrown by the target of an invocation.
---> System.NullReferenceException: Object reference not set to an instance of
an object. at Program.Main(Int32 start, Int32 len, String argument)
~~~

whereas with this code:

~~~
static void Main(string argument, int start, int len = 1)
~~~

You get this:

~~~
Required argument missing for command: slice

Usage:
  slice [options] <argument>

Arguments:
  <argument>

Options:
  --start <start>    start
  --len <len>        len [default: 1]
~~~

**Comment by jonsequitur** [comment]
This is as expected. 

Apologies if I'm over-explaining. The exception you're showing is happening in your handler code because `argument` is being passed by the `System.CommandLine` model binder as `null`. (`argument.Substring(start, len)` throws `NullReferenceException`.) DragonFruit allows this because the method signature declares the parameter `string argument = null`, meaning `null` is a valid input. Your `Main` method in this case would have to anticipate the possibility of that parameter being `null`. 

If you want the parser to prevent this from happening, the other method signature (`static void Main(string argument, int start, int len = 1)`) does that, as you noted. The parameters have to be reordered to satisfy the C# language rule that optional parameters can't precede non-optional parameters.

So given all of that, these two different method signatures tell DragonFruit how to set the argument's arity, in effect:

```csharp
static void Main(string argument, int start, int len = 1) { } // --> ArgumentArity.ExactlyOne
static void Main(int start, int len = 1, string argument = null) { }  // --> ArgumentArity.ZeroOrOne
```

Hopefully that all makes sense. 

I believe the sample code in the documentation works as advertised but if you find an example that doesn't please point it out.

**Comment by nu8** [comment]
The point is, I cant see why anyone would ever want to use this syntax:

~~~cs
static void Main(int start, int len = 1, string argument = null)
~~~

because when you do, the second you leave off `argument` youre going to get an
exception. Whereas with this:

~~~cs
static void Main(string argument, int start, int len = 1)
~~~

regardless what you do, worse case you will get a helpful usage printout. **So
why would anyone ever want to use the first syntax?** If the answer is (which
is my suspicion) "they wouldnt, its a pointless syntax", then I think that
example on that page I linked should be updated to the second example in my
comment here. A (very) common use case for command line programs is this:

~~~
command [flags] argument
~~~

where `argument` is required, and `flags` are optional. Do you really not have
experience with this use case? Because with this use case, the `argument = null`
examples are completely useless.

**Comment by jonsequitur** [comment]
Optional arguments are very common. A few examples of well-known commands with optional arguments:  `git push`, `git pull`, `git branch`, `npm install`, `dotnet build`.

(Again, if you make the argument optional, you have to handle the null case in your code.)

Another use case for the syntax of course is setting a default value:

```csharp
static void Main(int start, int len = 1, string argument = "")
```

**Comment by nu8** [comment]
I am not talking about optional arguments. I am talking about required
arguments. In that context, an `argument = null` syntax is pointless, because it
produces an exception rather than usage text.

**Comment by SeanTMill** [comment]
@jonsequitur How do you support something like git push, git pull, etc using the DragonFruit app model? What would the signature of the Main method look like to require a "command" with optional arguments?

**Comment by Kralizek** [comment]
@SeanTMill 

Does it have to? Commands and Options are already a very strong way to create CLIs like git.

I see DragonFruit to be used when creating console apps that are more straight forward. Like scheduled tasks.

**Comment by jonsequitur** [comment]
DragonFruit doesn't support subcommands (a.k.a. verbs). For now you need to use the System.CommandLine APIs directly, though we are working on a layer on top of that for building more complex tools in a more DragonFruity style.

@KathleenDollard

**Comment by SeanTMill** [comment]
@Kralizek 

No it doesn't have to, I just asked the question because this thread is about DrageFruit and @jonsequitur mentioned git push, git pull. So I thought I was missing something about what DragonFruit supported. I have just switched to using the APIs directly to get the support I need.
