### ISSUE TITLE
Help rendering fails on formatted option description

### ISSUE THREAD

**Issue by sfoslund** [dotnet/command-line-api#1068]
Depending on the size of the screen, help rendering fails if an option description contains new lines/ whitespace. For example, the following descriptions cause failures:
https://github.com/dotnet/sdk/blob/e2faebad758a7d38b5965cda755a17e9e9881599/src/Cli/dotnet/commands/dotnet-publish/LocalizableStrings.resx#L138
https://github.com/dotnet/sdk/blob/7d267abebfb4ff8b970158e38cd30045da85bd05/src/Cli/dotnet/commands/dotnet-test/LocalizableStrings.resx#L201

Error:
> System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.CommandLine.Help.HelpBuilder.SplitText(String text, Int32 width)
   at System.CommandLine.Help.HelpBuilder.<>c__DisplayClass35_0.<AppendRow>b__0(String element, Int32 index)
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.CommandLine.Help.HelpBuilder.AppendRow(IEnumerable`1 row, IReadOnlyList`1 columnWidths)
   at System.CommandLine.Help.HelpBuilder.AppendTable(IEnumerable`1 table, IReadOnlyList`1 columnWidths)
   at System.CommandLine.Help.HelpBuilder.AppendHelpItems(IReadOnlyCollection`1 helpItems)
   at System.CommandLine.Help.HelpBuilder.HelpSection.AddInvocation(HelpBuilder builder, IReadOnlyCollection`1 helpItems)
   at System.CommandLine.Help.HelpBuilder.HelpSection.WriteItems(HelpBuilder builder, String title, IReadOnlyCollection`1 usageItems, String description)
   at System.CommandLine.Help.HelpBuilder.AddOptions(ICommand command)
   at System.CommandLine.Help.HelpBuilder.Write(ICommand command)

**Comment by jonsequitur** [comment]
Can you provide a specific repro, e.g. what size console and which terminal will cause this to happen?

**Comment by sfoslund** [comment]
I'm seeing this with windows command prompt and it happens with most sizes I've used, including the default 120x30 window size.

**Comment by zpittmansf** [comment]
@jonsequitur I only saw this problem when I was using subcommand and the width was less than 125. Root > command > subcommand. Then I tried Root > Command and that was fine when less than 125 until I shrunk the width down to 59. 

I can make a n example repo if that helps.

**Comment by zpittmansf** [comment]
@jonsequitur just tried out 0.3.0-alpha.20567.1 (I believe that is the correct build) and I am still seeing 

`Unhandled exception. System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.CommandLine.Help.HelpBuilder.SplitText(String text, Int32 width)
   at System.CommandLine.Help.HelpBuilder.AppendDescription(String description)
   at System.CommandLine.Help.HelpBuilder.HelpSection.AddDescription(HelpBuilder builder, String description)
   at System.CommandLine.Help.HelpBuilder.HelpSection.WriteHeading(HelpBuilder builder, String title, String description)
   at System.CommandLine.Help.HelpBuilder.AddSynopsis(ICommand command)
   at System.CommandLine.Help.HelpBuilder.Write(ICommand command)
   at System.CommandLine.Invocation.ParseErrorResult.Apply(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.GetResultCode(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(IConsole console)
   at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console)
   at System.CommandLine.Parsing.ParserExtensions.InvokeAsync(Parser parser, String[] args, IConsole console)
...`

**Comment by zpittmansf** [comment]
> @jonsequitur just tried out 0.3.0-alpha.20567.1 (I believe that is the correct build) and I am still seeing
> 
> `Unhandled exception. System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex') at System.String.Substring(Int32 startIndex, Int32 length) at System.CommandLine.Help.HelpBuilder.SplitText(String text, Int32 width) at System.CommandLine.Help.HelpBuilder.AppendDescription(String description) at System.CommandLine.Help.HelpBuilder.HelpSection.AddDescription(HelpBuilder builder, String description) at System.CommandLine.Help.HelpBuilder.HelpSection.WriteHeading(HelpBuilder builder, String title, String description) at System.CommandLine.Help.HelpBuilder.AddSynopsis(ICommand command) at System.CommandLine.Help.HelpBuilder.Write(ICommand command) at System.CommandLine.Invocation.ParseErrorResult.Apply(InvocationContext context) at System.CommandLine.Invocation.InvocationPipeline.GetResultCode(InvocationContext context) at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(IConsole console) at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console) at System.CommandLine.Parsing.ParserExtensions.InvokeAsync(Parser parser, String[] args, IConsole console) ...`

I cloned with lastest master @a563074d874493d1f6a0617abb809a82c932a12f and the fix is definitely working. When I went to the azure build link and saw a 11/18 build with this same commit I just assumed the 11/18 build 0.3.0-alpha.20567.1 would include this commit. Just having trouble seeing if the daily build includes a specific commit. Sorry @jonsequitur.

**Comment by jonsequitur** [comment]
The build failed due to a signing issue we're experiencing. I'll post back with a build number containing the fix when it's available.
