### ISSUE TITLE
Option description in dotnet-dump collect throws exception

### ISSUE THREAD

**Issue by mikem8361** [dotnet/command-line-api#1115]
Our dotnet-dump tool throws an exception display the help for the collect subcommand:

`dotnet-dump collect --help`

```
Unhandled exception. System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.CommandLine.Help.HelpBuilder.SplitText(String text, Int32 width) in /_/src/System.CommandLine/Help/HelpBuilder.cs:line 418
   at System.CommandLine.Help.HelpBuilder.<>c__DisplayClass35_0.<AppendRow>b__0(String element, Int32 index) in /_/src/System.CommandLine/Help/HelpBuilder.cs:line 343
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.CommandLine.Help.HelpBuilder.AppendRow(IEnumerable`1 row, IReadOnlyList`1 columnWidths) in /_/src/System.CommandLine/Help/HelpBuilder.cs:line 343
   at System.CommandLine.Help.HelpBuilder.AppendTable(IEnumerable`1 table, IReadOnlyList`1 columnWidths) in /_/src/System.CommandLine/Help/HelpBuilder.cs:line 332
   at System.CommandLine.Help.HelpBuilder.AppendHelpItems(IReadOnlyCollection`1 helpItems) in /_/src/System.CommandLine/Help/HelpBuilder.cs:line 235
   at System.CommandLine.Help.HelpBuilder.HelpSection.AddInvocation(HelpBuilder builder, IReadOnlyCollection`1 helpItems) in /_/src/System.CommandLine/Help/HelpBuilder.cs:line 868
   at System.CommandLine.Help.HelpBuilder.HelpSection.WriteItems(HelpBuilder builder, String title, IReadOnlyCollection`1 usageItems, String description) in /_/src/System.CommandLine/Help/HelpBuilder.cs:line 831
   at System.CommandLine.Help.HelpBuilder.AddOptions(ICommand command) in /_/src/System.CommandLine/Help/HelpBuilder.cs:line 705
   at System.CommandLine.Help.HelpBuilder.Write(ICommand command) in /_/src/System.CommandLine/Help/HelpBuilder.cs:line 65
   at System.CommandLine.Invocation.HelpResult.Apply(InvocationContext context) in /_/src/System.CommandLine/Invocation/HelpResult.cs:line 13
   at System.CommandLine.Invocation.InvocationPipeline.GetResultCode(InvocationContext context) in /_/src/System.CommandLine/Invocation/InvocationPipeline.cs:line 73
   at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(IConsole console) in /_/src/System.CommandLine/Invocation/InvocationPipeline.cs:line 28
   at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console) in /_/src/System.CommandLine/Parsing/ParseResultExtensions.cs:line 20
   at System.CommandLine.Parsing.ParserExtensions.InvokeAsync(Parser parser, String[] args, IConsole console) in /_/src/System.CommandLine/Parsing/ParserExtensions.cs:line 33
   at Microsoft.Diagnostics.Tools.Dump.Program.<Main>(String[] args)
```
The option code that causes this exception:
```
        private static Option TypeOption() =>
            new Option(
                alias: "--type",
                description: @"The dump type determines the kinds of information that are collected from the process. There are several types: full - The largest dump containing all memory including the module images. heap - A large and relatively comprehensive dump containing module lists, thread lists, all stacks, exception information, handle information, and all memory except for mapped 
images. mini - A small dump containing module lists, thread lists, exception information and all stacks. If not specified 'full' is the default.")
            {
                Argument = new Argument<Dumper.DumpTypeOption>(name: "dump_type", getDefaultValue: () => Dumper.DumpTypeOption.Full)
            };
```

Changing/reformating the description string does prevent this exception.

**Comment by jonsequitur** [comment]
Which version of System.CommandLine are you using? We closed a similar-looking bug recently, #1068.

**Comment by mikem8361** [comment]
Version 2.0.0-beta1.20468.1.  I can try the latest.

**Comment by mikem8361** [comment]
Version 2.0.0-beta1.20601.7 did fix my problem. Thanks.
