### ISSUE TITLE
ArgumentException when using commands and global options

### ISSUE THREAD

**Issue by elgonzo** [dotnet/command-line-api#1219]
When using commands with global options that have an arity of max > 1, constructing the command line in a way where one option instance appears before the command while another instance of the same option appears after the command will cause an ArgumentException.

For example, with a command "_cmd_" and a global option "_--foo_" of type `int[]` (with an arity of max > 1), providing a command line like this will throw an ArgumentException:

`--foo 1 cmd --foo 2`

(On the other hand, using command lines like `cmd --foo 1 --foo 2` or `--foo 1 --foo 2 cmd`  will result in the expected `int[]{1,2}` array passed to the handler.)
<br>

**Code reproducing the the issue:**

    var option = new Option<int[]>("--foo", arity: ArgumentArity.ZeroOrMore);
    
    var rootCmd = new RootCommand
    {
        new Command("cmd")
        {
            Handler = CommandHandler.Create<int[]>(
                foo =>
                {
                    Console.WriteLine("Foo values:");
                    foreach (var v in foo) Console.WriteLine(v);
                }
            )
        }
    };

    rootCmd.AddGlobalOption(option);

    rootCmd.Invoke("--foo 1 cmd --foo 2");

<br>

**Expected behavior:**

Either the handler outputting
> Foo values
> 1
> 2

or, if such command line construct should not be supported, an error text should be printed.
<br>

**Actual behavior:**

ArgumentException when executing `rootCmd.Invoke("--foo 1 sub --foo 2");`

Exception stacktrace:

    at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
    at System.CommandLine.Parsing.SymbolResultCollatorVisitor.VisitOptionResult(OptionResult optionResult) in X:\Playground\System.CommandLine\src\System.CommandLine\Parsing\SymbolResultCollatorVisitor.cs:line 18
    at System.CommandLine.Parsing.SymbolResultVisitor.VisitInternal(SymbolResult node) in X:\Playground\System.CommandLine\src\System.CommandLine\Parsing\SymbolResultVisitor.cs:line 47
    at System.CommandLine.Parsing.SymbolResultVisitor.VisitInternal(SymbolResult node) in X:\Playground\System.CommandLine\src\System.CommandLine\Parsing\SymbolResultVisitor.cs:line 41
    ...

**Comment by elgonzo** [comment]
Closing because the mentioned global option APIs don't exist anymore.
