### ISSUE TITLE
InvalidOperationException ReadOnlySpan<int> cannot be bound

### ISSUE THREAD

**Issue by iesoftwaredeveloper** [dotnet/command-line-api#1284]
I am able to reproduce it when I am trying to use use an optional decimal and ComplexTypes.  This doesn't seem to occur if I do not use ComplexTypes.

I am using System.CommandLine 2.0.0-beta1.21215.1
Target Framework is net5.0

Providing the option on the command line is successful.

```
$ dotnet run -- --opt-decimal 123.456
ParseResult: [ system-commandline-decimal-exception [ --opt-decimal <123.456> ] ]
--opt-decimal 123.456
```

Not including the optional parameter on the command line results in the exception.

```
$ dotnet run
Unhandled exception: System.InvalidOperationException: The type System.ReadOnlySpan`1[System.Int32] cannot be bound
   at System.CommandLine.Binding.ModelBinder.CreateInstanceInternal(BindingContext bindingContext)
   at System.CommandLine.Binding.ModelBinder.GetBoundValue(IValueSource valueSource, BindingContext bindingContext, IValueDescriptor valueDescriptor, Boolean includeMissingValues, Type parentType)
   at System.CommandLine.Binding.ModelBinder.GetBoundValues(IDictionary`2 bindingSources, BindingContext bindingContext, IReadOnlyList`1 valueDescriptors, Boolean enforceExplicitBinding, Type parentType, Boolean includeMissingValues)
   at System.CommandLine.Binding.ModelBinder.GetBestConstructorAndArgs(BindingContext bindingContext)
   at System.CommandLine.Binding.ModelBinder.CreateInstanceInternal(BindingContext bindingContext)
   at System.CommandLine.Binding.ModelBinder.GetBoundValue(IValueSource valueSource, BindingContext bindingContext, IValueDescriptor valueDescriptor, Boolean includeMissingValues, Type parentType)
   at System.CommandLine.Binding.ModelBinder.GetBoundValues(IDictionary`2 bindingSources, BindingContext bindingContext, IReadOnlyList`1 valueDescriptors, Boolean enforceExplicitBinding, Type parentType, Boolean includeMissingValues)
   at System.CommandLine.Binding.ModelBinder.UpdateInstanceInternalNotifyIfNonDefaultsUsed[T](T instance, BindingContext bindingContext)
   at System.CommandLine.Binding.ModelBinder.InstanceFromSpecificConstructor(BindingContext bindingContext, ConstructorDescriptor constructor, IReadOnlyList`1 boundValues, Boolean& nonDefaultsUsed)
   at System.CommandLine.Binding.ModelBinder.CreateInstanceInternal(BindingContext bindingContext)
   at System.CommandLine.Binding.ModelBinder.GetBoundValue(IValueSource valueSource, BindingContext bindingContext, IValueDescriptor valueDescriptor, Boolean includeMissingValues, Type parentType)
   at System.CommandLine.Binding.ModelBinder.GetBoundValues(IDictionary`2 bindingSources, BindingContext bindingContext, IReadOnlyList`1 valueDescriptors, Boolean enforceExplicitBinding, Type parentType, Boolean includeMissingValues)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

Here is a quick sample program to reproduce.
```
using System.CommandLine;
using System.CommandLine.Invocation;
using System.CommandLine.IO;
using System.CommandLine.Parsing;

namespace system_commandline_decimal_exception
{
    /// <summary>
    /// Successful example
    /// 
    /// $ dotnet run -- --opt-decimal 123.456
    /// ParseResult: [ system-commandline-decimal-exception [ --opt-decimal <123.456> ] ]
    /// --opt-decimal 123.456
    /// 
    /// Exception
    /// 
    /// $ dotnet run -- 
    /// </summary>
    class Program
    {
        static void Main(string[] args)
        {
            var rootCommand = new RootCommand()
            {
                Description = "Console app to demonstrate System.CommandLine complex type exception"
            };
            rootCommand.Add(new Option<decimal>(new[] { "--opt-decimal" }, description: "A decimal option"));
            rootCommand.Handler = CommandHandler.Create((ParseResult parseResult, IConsole console, ComplexType options) =>
               {
                   console.Out.WriteLine($"{parseResult}");
                   console.Out.WriteLine($"--opt-decimal {options.OptDecimal}");
               });

            rootCommand.InvokeAsync(args);
        }
    }

    public class ComplexType
    {
        public decimal OptDecimal { get; set; }
    }

}
```

_Originally posted by @iesoftwaredeveloper in https://github.com/dotnet/command-line-api/issues/1137#issuecomment-846255778_

**Comment by iesoftwaredeveloper** [comment]
The work around for this is currently to not include any optional commands that are of type decimal in a complex type.  

There are a couple of work-arounds.  

You can include the decimal in the ComplexType, but do not include any setters.  Instead provide a constructor.  Do not include the decimal parameter in the constructor.  Then set the property using some other mechanism.

The other work-around is to use setters, but do not include the decimal property in the ComplextType at all. In this case you still need to deal with the decimal option outside of the ComplexType.
