### ISSUE TITLE
Allow customizing apartment model when using System.CommandLine.DragonFruit

### ISSUE THREAD

**Issue by andrewhickman** [dotnet/command-line-api#1322]
Hi,

I tried creating a small command line app which launches a browser using the [WebBrowser](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.webbrowser?view=net-5.0) class. 

The following code

<details>
<summary>
Program.cs
</summary>

```
using System;
using System.Windows.Forms;

namespace MyApp
{
    public class Program
    {
        [STAThread]
        public static void Main()
        {
            new WebBrowser();
        }
    }
}
```
</details>

<details>
<summary>
MyApp.csproj
</summary>

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <DisableWinExeOutputInference>true</DisableWinExeOutputInference>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine.DragonFruit" Version="0.3.0-alpha.21216.1" />
  </ItemGroup>

</Project>
```

</details>

complains it needs to run in a single-threaded apartment even though I marked `Main` with `[STAThread]`:

<details>
<summary>
Stacktrace
</summary>

```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Threading.ThreadStateException: ActiveX control '8856f961-340a-11d0-a96b-00c04fd705a2' cannot be instantiated because the current thread is not in a single-threaded apartment.
   at System.Windows.Forms.WebBrowserBase..ctor(String clsidString)
   at System.Windows.Forms.WebBrowser..ctor()
   at MyApp.Program.Main() in D:\<redacted>\Program.cs:line 11
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass6_0.<<ConfigureConsole>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```
</details>

Removing the Dragonfruit dependency makes the code work. I assume its re-writing my Main function to run in another thread which is using a different apartment model? This should probably be configurable

**Comment by jonsequitur** [comment]
Yes, DragonFruit's real entry point is generated: 

https://github.com/dotnet/command-line-api/blob/f62aa17ab2ab09f26e679953a198117b4fa809c7/src/System.CommandLine.DragonFruit/targets/System.CommandLine.DragonFruit.targets#L24-L42 

It might be possible to detect the project type and emit different code. Ideas?

**Comment by andrewhickman** [comment]
I actually ran into the same issue using `System.CommandLine` directly, so I'm not sure whether the issue is with Dragonfruit specifically.

I ended up doing something like

```csharp
Options options = null;
command.Handler = CommandHandler.Create((Options o) => options = o);

var exitCode = rootCommand.Invoke(args);
if (options == null)
{
  return exitCode;
}

// Do work on the main thread here
```

Doing work inside the command handler directly also seemed to get executed on a different thread, so I had the same issue there

**Comment by Keboo** [comment]
Yea this is sort of a generic issue when working with UI frameworks like WinForms or WPF. The main thread need the STA apartment state, but that is not something that you get by default. In a normal desktop project the default templates will setup the main method with the [[STAThread]](https://docs.microsoft.com/dotnet/api/system.stathreadattribute) to handle it for you. However, once you take control of the Main method, it is up to you to manage it yourself. This library doesn't make any attempts to manage the apartment state of the threads, and as a result you get the default console app behavior.  You should see identical behavior if you simply wrote your own `public static void Main(string[] args)` method (which it sounds like is what you tried).

To address the problem you need to start up your own Thread and set the apartment state on it. Once you do this, you can then do all f the normal WinForms stuff and handle the interactions. I have put together a [small sample](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/System.CommandLine/System.CommandLine.WinForms) you can take a look at as an example.

I am not really sure if there is much this library can/should do here. I would expect that if code is going to require an STA thread, I would put the code to spin the thread either within the command's handler, or in the strongly-typed main method (if using Dragon Fruit).

**Comment by andrewhickman** [comment]
I noticed that using `InvokeAsync` actually did run the handler on the same thread - the small change in #1324 makes Invoke use the same behaviour
