### ISSUE TITLE
Concurrency issue in SuggestionSource

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/command-line-api#1406]
I have a set of unit tests which cover my program's Main method, ensuring the argument parsing & validation works correctly.

They sometimes file with stack traces similar to this:

```
  Error Message:
   System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
  Stack Trace:
     at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at System.CommandLine.DictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 source, TKey key, Func`2 create) in /_/src/System.CommandLine/DictionaryExtensions.cs:line 12
   at System.CommandLine.Suggestions.SuggestionSource.ForType(Type type) in /_/src/System.CommandLine/Suggestions/SuggestionSource.cs:line 23
   at System.CommandLine.Argument.get_Suggestions() in /_/src/System.CommandLine/Argument.cs:line 99
   at System.CommandLine.Argument.GetSuggestions(ParseResult parseResult, String textToMatch) in /_/src/System.CommandLine/Argument.cs:line 214
   at System.CommandLine.Help.HelpBuilder.GetArgumentDescriptor(IArgument argument) in /_/src/System.CommandLine/Help/HelpBuilder.cs:line 507
   at System.CommandLine.Help.HelpBuilder.GetHelpItem(IIdentifierSymbol symbol) in /_/src/System.CommandLine/Help/HelpBuilder.cs:line 409
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.CommandLine.Help.HelpBuilder.AddOptions(ICommand command) in /_/src/System.CommandLine/Help/HelpBuilder.cs:line 167
   at System.CommandLine.Help.HelpBuilder.Write(ICommand command) in /_/src/System.CommandLine/Help/HelpBuilder.cs:line 44
   at System.CommandLine.Invocation.ParseErrorResult.Apply(InvocationContext context) in /_/src/System.CommandLine/Invocation/ParseErrorResult.cs:line 29
   at System.CommandLine.Invocation.InvocationPipeline.GetExitCode(InvocationContext context) in /_/src/System.CommandLine/Invocation/InvocationPipeline.cs:line 72
   at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(IConsole console) in /_/src/System.CommandLine/Invocation/InvocationPipeline.cs:line 28
   at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console) in /_/src/System.CommandLine/Parsing/ParseResultExtensions.cs:line 20
   at System.CommandLine.Parsing.ParserExtensions.InvokeAsync(Parser parser, String[] args, IConsole console) in /_/src/System.CommandLine/Parsing/ParserExtensions.cs:line 33
[...]
--- End of stack trace from previous location ---
```

Looks like this is a side-effect of #1260.

I'm not sure how big the perf gain of #1260 is, but if possible, I'd like to be able to run my unit tests in parallel.

**Comment by elgonzo** [comment]
https://github.com/dotnet/command-line-api/pull/1260 also explicitly mentions that types like SuggestionSource are not considered to be thread-safe.

Thus, make sure your different unit tests don't operate on the same CommandLineBuilder and/or SuggestionSource instances.
If your testing framework by itself does not isolate tests from each other, i suggest switching to one that does (like for example the xunit framework).

**Comment by qmfrederik** [comment]
Yes, these tests all construct a new instance of the `CommandLineBuilder` class, and I'd expect it to be safe to use different instances of the `CommandLineBuilder` class in parallel.

**Comment by qmfrederik** [comment]
Thanks, @jonsequitur !
