### ISSUE TITLE
Different (parsing) behavior of long and short options

### ISSUE THREAD

**Issue by FroggieFrog** [dotnet/command-line-api#1445]
I haven't found a similiar issue that is already reported.
When invoking my app with the long option (`--directory`) everything works correct. Even the false input `--directory_"C:\"` is handled correct.

When invoking with the short option (`-d`) the behavior of the parser/binding changes.
- input `-d:"C:\"` leads to a crash
- input `-d_"C:\"` leads to wrong result

#### output as text
<details>
  <summary>Click to expand!</summary> 

```console
dotnet run --configuration:"Release" -- [parse] dummy --directory "C:\"
[ app [ dummy [ --directory <C:\> ] ] ]

dotnet run --configuration:"Release" -- [parse] dummy --directory="C:\"
[ app [ dummy [ --directory <C:\> ] ] ]

dotnet run --configuration:"Release" -- [parse] dummy --directory:"C:\"
[ app [ dummy [ --directory <C:\> ] ] ]

dotnet run --configuration:"Release" -- [parse] dummy --directory_"C:\"
[ app ![ dummy ] ]   ???--> --directory_C:\

dotnet run --configuration:"Release" -- [parse] dummy -d "C:\"
[ app [ dummy [ -d <C:\> ] ] ]

dotnet run --configuration:"Release" -- [parse] dummy -d="C:\"
[ app [ dummy [ -d <C:\> ] ] ]

dotnet run --configuration:"Release" -- [parse] dummy -d:"C:\"
Stopped program because of exception
Unhandled exception. System.AggregateException: One or more errors occurred. (Exception has been thrown by the target of an invocation.)
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.DirectoryInfo..ctor(String path)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at System.CommandLine.Binding.ArgumentConverter.ConvertString(IArgument argument, Type type, String value)
   at System.CommandLine.Binding.ArgumentConverter.ConvertObject(IArgument argument, Type type, Object value)
   at System.CommandLine.Binding.ArgumentConverter.TryConvertArgument(ArgumentResult argumentResult, Object& value)
   at System.CommandLine.Parsing.ArgumentResult.Convert(IArgument argument)
   at System.CommandLine.Parsing.ArgumentResult.GetArgumentConversionResult()
   at System.CommandLine.Parsing.ParseResultVisitor.ValidateAndConvertArgumentResult(ArgumentResult argumentResult)
   at System.CommandLine.Parsing.ParseResultVisitor.ValidateAndConvertOptionResult(OptionResult optionResult)
   at System.CommandLine.Parsing.ParseResultVisitor.Stop(SyntaxNode node)
   at System.CommandLine.Parsing.SyntaxVisitor.Visit(SyntaxNode node)
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   at System.CommandLine.CommandExtensions.GetInvocationPipeline(Command command, String[] args)
   at System.CommandLine.CommandExtensions.InvokeAsync(Command command, String[] args, IConsole console)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at app.Program.Main(String[] args)
   at app.Program.<Main>(String[] args)

dotnet run --configuration:"Release" -- [parse] dummy -d_"C:\"
[ app [ dummy [ -d <_C:\> ] ] ]
```
</details>

#### used code
<details>
  <summary>Click to expand!</summary> 

```csharp
//inside of Main
var rootCommand = new RootCommand();
addDummyCommandCommand(rootCommand);

return rootCommand.InvokeAsync(args).Result;


private static void addDummyCommandCommand(RootCommand rootCommand)
{
    var directoryOption = new Option<System.IO.DirectoryInfo>(aliases: new[] { "--directory", "-d" })
    {
        IsRequired = true,
        Arity = ArgumentArity.ExactlyOne
    };

    var dummyCommand = new Command("dummy") { directoryOption };
    dummyCommand.Handler = CommandHandler.Create<System.IO.DirectoryInfo, IConsole>((directory, console) =>
    {
        console.Out.Write($"Command used: dummy{Environment.NewLine}\t{nameof(directory)}: \"{directory?.FullName}\"");
    });

    rootCommand.AddCommand(dummyCommand);
}
```
</details>

#### output as image
<details>
  <summary>Click to expand!</summary> 

![parser_error](https://user-images.githubusercontent.com/6222752/137877512-7f4015d0-19b1-40e4-96d5-e036caee852c.png)
</details>

**Comment by elgonzo** [comment]
Checking against the newer 2.0.0-beta1.21514.1 (from the daily builds feed), `-d:"C:\"` is properly parsed:
```
dotnet run --configuration:"Release" -- [parse] dummy -d:"C:\"
[ ConsoleApp1 [ dummy [ -d <C:> ] ] ]
```
All other variants of command line invocation as described in the report still behave the same.

**Comment by jonsequitur** [comment]
At the start of the program I added this:

```cs
foreach (var arg in args)
{
    Console.WriteLine(arg);
}
```

You can see here what `Main` received from the shell:

![image](https://user-images.githubusercontent.com/547415/137981168-58e9ac1c-c595-4a4e-a5d8-5eaf229fab56.png)
