### ISSUE TITLE
Behavior change between beta2 and beta3 when parsing nullable enum values

### ISSUE THREAD

**Issue by adrianbanks** [dotnet/command-line-api#1621]
[Compiled using .Net 6.0]

## Summary

The behavior of parsing nullable enum values has changed between `beta2` and `beta3`. Was this intentional, and if so, how do I fix it?

I'm using nullable enum values as I want to know when a value has been set vs a default value being used (e.g. not specified vs explicitly set vs a default value being assigned to the enum field by C#).

## What is broken?

The behavior of parsing nullable enum values has changed between `beta2` (2.0.0-beta2.21617.1) and `beta3` (2.0.0-beta3.22103.3, but the same thing happens also with 2.0.0-beta3.22106.2).

In beta2, a nullable enum would parse to a `null` when no value was specified, and parse correctly when a value was specified.

In beta3, it still parses to a `null` when no value is specified, but now crashes when a value is specified.

## Reproduction steps

Using the example code below and `beta2`:

`SystemCommandLineBug.exe` outputs `Value: [null]`

`SystemCommandLineBug.exe --enumValue valueb` outputs `Value: ValueB`

Using the same code and `beta3`:

`SystemCommandLineBug.exe` outputs `Value: [null]`

`SystemCommandLineBug.exe --enumValue valueb` crashes:

```
Error: System.InvalidOperationException: Cannot parse argument 'valueb' for option '--enumValue' as expected type 'System.Nullable`1[SystemCommandLineBug.MyEnum]'.
   at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
   at System.CommandLine.Parsing.OptionResult.GetValueOrDefault[T]()
   at System.CommandLine.Parsing.SymbolResult.GetValueForOption[T](Option`1 option)
   at System.CommandLine.Parsing.ParseResult.GetValueForOption[T](Option`1 option)
   at SystemCommandLineBug.MyArgsBinder.GetBoundValue(BindingContext bindingContext) in D:\code\spikes\SystemCommandLineBug\Program.cs:line 34
   at System.CommandLine.Binding.BinderBase`1.System.CommandLine.Binding.IValueSource.TryGetValue(IValueDescriptor valueDescriptor, BindingContext bindingContext, Object& boundValue)
   at System.CommandLine.Handler.GetValueForHandlerParameter[T](IValueDescriptor[] symbols, Int32& index, InvocationContext context)
   at System.CommandLine.Handler.<>c__DisplayClass1_0`1.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.<>c__DisplayClass2_0.<.ctor>g__Handle|0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
```

<details>
  <summary>Full example code that demonstrates the issue</summary>
  
  ```csharp
using System.CommandLine;
using System.CommandLine.Binding;
using System.CommandLine.Builder;
using System.CommandLine.Parsing;

namespace SystemCommandLineBug
{
    internal static class Program
    {
        public static void Main(string[] args)
        {
            void RunAction(MyArgs a) => Console.WriteLine($"Value: {a.MyEnumValue?.ToString() ?? "[null]"}");

            var argsBinder = new MyArgsBinder();
            var rootCommand = new RootCommand();
            rootCommand.SetHandler((Action<MyArgs>) RunAction, argsBinder);
            argsBinder.Initialise(rootCommand);

            var builder = new CommandLineBuilder(rootCommand)
                .UseDefaults()
                .UseExceptionHandler((e, _) => Console.WriteLine($"Error: {e}"));

            var parser = builder.Build();
            parser.Invoke(args);
        }
    }

    internal sealed class MyArgsBinder : BinderBase<MyArgs>
    {
        private readonly Option<MyEnum?> _myEnumValue = new("--enumValue");

        protected override MyArgs GetBoundValue(BindingContext bindingContext)
        {
            return new MyArgs
            {
                MyEnumValue = bindingContext.ParseResult.GetValueForOption(_myEnumValue),
            };
        }

        public void Initialise(RootCommand rootCommand)
        {
            rootCommand.Add(_myEnumValue);
        }
    }

    internal sealed class MyArgs
    {
        public MyEnum? MyEnumValue { get; set; }
    }

    internal enum MyEnum
    {
        ValueA,
        ValueB,
        ValueC
    }
}
  ```
</details>

**Comment by jonsequitur** [comment]
I'm guessing this is the same root cause as the issues fixes by #1615 and #1619.

**Comment by adrianbanks** [comment]
> I'm guessing this is the same root cause as the issues fixes by #1615 and #1619.

From debugging it, it seems to be caused by the type checking in [`ArgumentConverter`](https://github.com/dotnet/command-line-api/blob/main/src/System.CommandLine/Binding/ArgumentConverter.cs#L42) - there isn't a type converter registered for the nullable enum type, and the nullable type isn't an enum (`type.IsEnum`), so the result of the conversion is always a failure.
