### ISSUE TITLE
Custom Command is missing an Argument or Option for the parameter at position 0

### ISSUE THREAD

**Issue by trockefeller-pathway** [dotnet/command-line-api#1667]
I am trying to make a custom command, and with the latest version of `System.CommandLine` I can't get it to work. I may be configuring my custom command incorrectly, but a very simplified version of the code is listed below.

```csharp
using System.CommandLine;

var rootCommand = new RootCommand { new CustomCommand() };
rootCommand.Description = "Testing custom commands.";
rootCommand.Invoke(args);

class CustomCommand : Command
{
    public CustomCommand() : base("CustomCommand", "Tests a custom command with a single positional argument.")
    {
        var positionalArgument = new Argument("PositionalArgument", "An argument that is passed in by position.");
        this.SetHandler<string>(positionalArgument => doStuff(positionalArgument), positionalArgument);
        AddArgument(positionalArgument);
    }

    private void doStuff(string positionalArgument)
    {
        Console.WriteLine(positionalArgument);
    }
}
```

When I use the above code with the arguments "CustomCommand HelloWorld" I am getting the following error.

> Unhandled exception: System.ArgumentException: The SetHandler call for command 'CustomCommand' is missing an Argument or Option for the parameter at position 0. Did you mean to pass one of these?
Argument<String> PositionalArgument
   at System.CommandLine.Handler.GetValueForHandlerParameter[T](IValueDescriptor[] symbols, Int32& index, InvocationContext context)
   at System.CommandLine.Handler.<>c__DisplayClass1_0`1.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.<>c__DisplayClass2_0.<.ctor>g__Handle|0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by jonsequitur** [comment]
You need to pass `positionalArgument` as a second parameter to `SetHandler`. You can see more information about this API here: https://github.com/dotnet/command-line-api/issues/1537

**Comment by trockefeller-pathway** [comment]
Sorry, I did have that second parameter passed in in my original code, and adding that second parameter fixed things in my sample project, but my original code was still failing. I found that it fails if I use `Argument` instead of `Argument<string>` It's this expected behavior, and the solution is I just need to use `Argument<string>`?

I updated the code above to represent how it was failing in my original code.

**Comment by jonsequitur** [comment]
You should use `Argument<string>` if possible. If not, we're interested to know why you might need the non-generic version. We're considering removing it unless there are strong use cases that favor keeping it.

**Comment by trockefeller-pathway** [comment]
I don't think I need to use the non-generic version. I just upgraded from a version where that wasn't required, and I hadn't updated all of my Arguments and Options to use the more explicit generic types. I think if the non-generic versions were removed it would help make it easier to write the code correctly.
