### ISSUE TITLE
Nullable integer argument parsing failed with multiples arguments

### ISSUE THREAD

**Issue by oblaise** [dotnet/command-line-api#1669]
When I use a single nullable int argument the parsing is working as expected. If the argument is positioned after a first required argument parsing is failing if optional int value isn't provided.

```c#
#r "nuget:System.CommandLine,*-*"

using System.CommandLine;
using System.CommandLine.Builder;
using System.CommandLine.Invocation;
using System.CommandLine.Parsing;


Argument<int?> argInt = new Argument<int?>("int");

RootCommand cmd1 = new RootCommand()
{
    argInt,
};

cmd1.SetHandler<int?>((i)=>Console.WriteLine($"cmd1: {(i is null ? "<null>":i)}"),argInt);
var parser1 = new CommandLineBuilder(cmd1).Build();
parser1.Invoke("1"); // It's OK
parser1.Invoke(""); // It's OK

Argument<string> argString = new Argument<string>("string");
Argument<int?> argInt2 = new Argument<int?>("int");

RootCommand cmd2 = new RootCommand()
{
    argString,
    argInt2,
};

cmd2.SetHandler<string,int?>((s,i)=>Console.WriteLine($"cmd2: {s}, {(i is null ? "<null>":i)}"),argString,argInt2);
var parser2 = new CommandLineBuilder(cmd2).Build();
parser2.Invoke("string 2"); // It's OK
parser2.Invoke("string"); // It's NOK

```

Result:
```
Installed Packages
System.CommandLine, 2.0.0-beta3.22114.1
cmd1: 1

cmd1: <null>

cmd2: string, 2

Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.CommandLine.Binding.ArgumentConverter.<>c__DisplayClass4_0.<GetConverter>g__ConvertSingleString|0(ArgumentResult result, Object& value)
   at System.CommandLine.Parsing.ArgumentResult.Convert(Argument argument)
   at System.CommandLine.Parsing.ArgumentResult.GetArgumentConversionResult()
   at System.CommandLine.Parsing.ParseResultVisitor.ValidateAndConvertArgumentResult(ArgumentResult argumentResult)
   at System.CommandLine.Parsing.ParseResultVisitor.Stop()
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   at System.CommandLine.Parsing.ParserExtensions.Invoke(Parser parser, String[] args, IConsole console)
   at System.CommandLine.Parsing.ParserExtensions.Invoke(Parser parser, String commandLine, IConsole console)
   at Submission#8.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
```

**Comment by jonsequitur** [comment]
This bug has been fixed in the latest System.CommandLine builds but not yet in .NET Interactive (which carries its own, slightly older version which it uses for magic command parsing.)

**Comment by oblaise** [comment]
You mean builds that aren't already part of any nuget ? 
I tried the same code on .net6 with latest nuget (https://www.nuget.org/packages/System.CommandLine/2.0.0-beta3.22114.1) and I have also an error but different:
```
cmd1: 1
cmd1: <null>
cmd2: string, 2
Unhandled exception. System.InvalidOperationException: Cannot parse argument '' for command 'testNullableInt' as expected type 'System.Int32'.
   at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
   at System.CommandLine.Parsing.ArgumentResult.GetValueOrDefault[T]()
   at System.CommandLine.Parsing.SymbolResult.GetValueForArgument[T](Argument`1 argument)
   at System.CommandLine.Parsing.ParseResult.GetValueForArgument[T](Argument`1 argument)
   at System.CommandLine.Parsing.ParseResult.GetValueFor[T](IValueDescriptor`1 symbol)
   at System.CommandLine.Handler.GetValueForHandlerParameter[T](IValueDescriptor[] symbols, Int32& index, InvocationContext context)
   at System.CommandLine.Handler.<>c__DisplayClass2_0`2.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.<>c__DisplayClass2_0.<.ctor>g__Handle|0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(IConsole console)
   at System.CommandLine.Parsing.ParseResultExtensions.Invoke(ParseResult parseResult, IConsole console)
   at System.CommandLine.Parsing.ParserExtensions.Invoke(Parser parser, String[] args, IConsole console)
   at System.CommandLine.Parsing.ParserExtensions.Invoke(Parser parser, String commandLine, IConsole console)```

**Comment by jonsequitur** [comment]
It's been published.
