### ISSUE TITLE
Allow an option to not add an alias every time a RootCommand receives --name as a parameter so that it is possible to have name with spaces

### ISSUE THREAD

**Issue by ritanorinho** [dotnet/command-line-api#1705]
When a RootCommand receives --name as an argument, an alias is added. However, it is not possible to have an alias with spaces. So, it would be interesting to allow having --name as an argument without adding an alias.

**Comment by jonsequitur** [comment]
Typically if someone wants to pass an argument with spaces they wrap the argument in quotes:

```console
> myapp --name "this will all be parsed as a single token"
```

Could you give an example of the command line arguments you're trying to parse and what it's doing differently from the way you would like?

**Comment by almeidev** [comment]
Detected on NuGet package version **2.0.0-beta1.20574.7**.

Code example reproducing the behavior:
```csharp
using System.CommandLine;
using System.CommandLine.Invocation;

var rootCommand = new RootCommand();
rootCommand.AddCommand(new CmdCommand());
return await rootCommand.InvokeAsync(args);

class CmdCommand : Command
{
    public CmdCommand() : base("cmd")
    {
        Add(new Option<string>(new[] { "--name" }));
        Handler = CommandHandler.Create(typeof(CmdCommand).GetMethod(nameof(CmdCommand.CmdHandler)), this);
    }

    public void CmdHandler(string name)
    {
        System.Console.WriteLine("Running command handler...");
        System.Console.WriteLine(name);
    }
}
```

Calling `CommandLineTesting cmd --name "abc xyz"` causes:
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: CmdCommand alias cannot contain whitespace: "ads asd" (Parameter 'alias')
   at System.CommandLine.Symbol.ThrowIfAliasIsInvalid(String alias)
   at System.CommandLine.Command.AddAliasInner(String alias)
   at System.CommandLine.NamedSymbol.set_Name(String value)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.InvokeOneParameter(Object obj, BindingFlags invokeAttr, Binder binder, Object parameter, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at System.CommandLine.Binding.ModelBinder.UpdateInstanceInternalNotifyIfNonDefaultsUsed[T](T instance, BindingContext bindingContext)
   at System.CommandLine.Binding.ModelBinder.UpdateInstance[T](T instance, BindingContext bindingContext)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by jonsequitur** [comment]
Thanks, I understand what's happening now. 

Because you're telling the model binder to use an instance of your derived `Command` type, it's setting the `Command.Name` property based on the `--name` option, and `Command.Name` doesn't allow whitespace.

One simple way to avoid this is to make your handler static and not pass in the current instance. This should work:

```csharp
    public class CmdCommand : Command
    {
        public CmdCommand() : base("cmd")
        {
            Add(new Option<string>(new[] { "--name" }));
            Handler = CommandHandler.Create(typeof(CmdCommand).GetMethod(nameof(CmdHandler)));
        }

        public static void CmdHandler(string name)
        {
            Console.WriteLine("Running command handler...");
            Console.WriteLine(name);
        }
    }
```

**Comment by almeidev** [comment]
Thanks for the suggestion.
Unfortunately, in our real scenario we need to call an instance method from the Handler, so without much refactoring it would not be possible to make the Handler method static.

In the meantime we tested another approach, using a custom handler parameters class. This way the name binding seems to work properly, correctly filling the parameters class properties, including the `name` one.

```csharp
class CmdCommand : Command
{
    public CmdCommand() : base("cmd")
    {
        Add(new Option<string>(new[] { "--name" }));
        Handler = CommandHandler.Create((CommandParams x) => CmdHandler(x));
    }

    public class CommandParams
    {
        public string Name { get; set; }
    }

    public void CmdHandler(CommandParams commandParams)
    {
        System.Console.WriteLine("Running command handler...");
        NonStaticMethod();
        System.Console.WriteLine(commandParams.Name);
    }

    private void NonStaticMethod()
    {
        // something...
    }
}
```

**Comment by jonsequitur** [comment]
That works too. Just be aware that with this approach the binder will still try mutate your `CmdCommand` instance (if you pass `this` to `CommandHandler.Create` or create another instance of it (if you don't.)
