### ISSUE TITLE
3 arguments with custom parse functions cause an exception

### ISSUE THREAD

**Issue by Tunduk** [dotnet/command-line-api#1779]
Hi! 
I think it's continue of this [issue](https://github.com/dotnet/command-line-api/issues/1759)

If create a command that accept 3 arguments with custom parse functions it'll fail. 
If command called with 1 token then 3rd argument will return empty array. If command called with more that 1 argument (like "1 2 3") then it'll throw an exception

Test code with an example [test.txt](https://github.com/dotnet/command-line-api/files/8974308/test.txt)

I am not very familiar with System.CommandLine code but I think the problem in `ParseOperation.ParseCommandArguments` function. Third argument isn't added because of arity of second argument.

Bug was found during review this [PR ](https://github.com/Tunduk/sdk/pull/1)

Let me know if you need more information.

**Comment by jonsequitur** [comment]
Thanks for opening the issue, @Tunduk!

I just verified that with the fix for #1759, your sample test also passes, so I'm closing this as a duplicate.

**Comment by Tunduk** [comment]
@jonsequitur Sorry, maybe I am doing something wrong. But I took last commit from main (4712b0cb) added my test and it failed. 
I also tried with branch "fix-1759" from your fork. The same result. 
Exception: 
```
System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.CommandLine.Parsing.ParseResultVisitor.ValidateAndConvertArgumentResults(IReadOnlyList`1 arguments, Int32 commandArgumentResultCount) in C:\Users\permi\Sources\open-source\command-line-api\src\System.CommandLine\Parsing\ParseResultVisitor.cs:line 267
   at System.CommandLine.Parsing.ParseResultVisitor.Stop() in C:\Users\permi\Sources\open-source\command-line-api\src\System.CommandLine\Parsing\ParseResultVisitor.cs:line 251
   at System.CommandLine.Parsing.ParseResultVisitor.Visit(SyntaxNode node) in C:\Users\permi\Sources\open-source\command-line-api\src\System.CommandLine\Parsing\ParseResultVisitor.cs:line 56
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput) in C:\Users\permi\Sources\open-source\command-line-api\src\System.CommandLine\Parsing\Parser.cs:line 64
   at System.CommandLine.Parsing.ParserExtensions.Parse(Parser parser, String commandLine) in C:\Users\permi\Sources\open-source\command-line-api\src\System.CommandLine\Parsing\ParserExtensions.cs:line 68
   at System.CommandLine.CommandExtensions.Parse(Command command, String commandLine) in C:\Users\permi\Sources\open-source\command-line-api\src\System.CommandLine\CommandExtensions.cs:line 102
   at System.CommandLine.Tests.ArgumentTests.Tunduk_Test() in C:\Users\permi\Sources\open-source\command-line-api\src\System.CommandLine.Tests\ArgumentTests.cs:line 767
```
`git log --oneline` result
```
4712b0cb (HEAD -> main, origin/main, origin/HEAD) fix #1768
de202297 Add support for timeout in process termination handling (#1756)
eaad2347 Fix #1759 (#1767)
15716023 remove outdated docs (#1766)
3021ce96 Update readme.md
209b724a (tag: 2.0.0-beta4.22272.1) bump version to beta4
```
I checked my test again, seems like it should pass. 

Could you check again, please? I think the issue still remains unresolved.
Or maybe my test is wrong but it's a simpler version of code from PR

**Comment by jonsequitur** [comment]
Sorry for the confusion. I ran your sample code the other day and my test runner swore to me that it passed but it must have had its fingers crossed behind its back.

**Comment by Tunduk** [comment]
Please, don't punish your test runner very hard =)
Thanks a lot for your help!

**Comment by Tunduk** [comment]
@jonsequitur Hi!
I found some problems with token shifting.
Tests for validation [tests.txt](https://github.com/dotnet/command-line-api/files/9048484/tests.txt)

If you need a new issue for this I'll create it.

**Comment by jeffhandley** [comment]
This works now with 2.0.0-beta5+.
