### ISSUE TITLE
Custom help problem

### ISSUE THREAD

**Issue by tamasg** [dotnet/command-line-api#1791]
Hi,

I am new here. I've tried several things and I'm having trouble with the custom help. The example given in the documentation throws an exception. [https://docs.microsoft.com/en-us/dotnet/standard/commandline/customize-help#add-or-replace-help-sections](https://docs.microsoft.com/en-us/dotnet/standard/commandline/customize-help#add-or-replace-help-sections)

My code:
```csharp
using Spectre.Console;
using System.CommandLine;
using System.CommandLine.Builder;
using System.CommandLine.Help;

namespace SampleCommandLineCustomHelp;

public static class Program
{
    public static async Task<int> Main(string[] args)
    {
        var fileOption = new Option<FileInfo>(
            "--file",
            description: "The file to print out.",
            getDefaultValue: () => new FileInfo("scl.runtimeconfig.json"));
        var lightModeOption = new Option<bool>(
            "--light-mode",
            description: "Determines whether the background color will be black or white");
        var foregroundColorOption = new Option<ConsoleColor>(
            "--color",
            description: "Specifies the foreground color of console output",
            getDefaultValue: () => ConsoleColor.White);

        fileOption.ArgumentHelpName = "<FILEPATH>";

        var rootCommand = new RootCommand("Read a file")
        {
            fileOption,
            lightModeOption,
            foregroundColorOption
        };
        
        rootCommand.SetHandler((file, lightMode, color) =>
        {
            Console.BackgroundColor = lightMode ? ConsoleColor.White : ConsoleColor.Black;
            Console.ForegroundColor = color;
            Console.WriteLine($"--file = {file?.FullName}");
            Console.WriteLine($"File contents:\n{file?.OpenText().ReadToEnd()}");
        },
        fileOption,
        lightModeOption,
        foregroundColorOption);
        
        var parser = new CommandLineBuilder(rootCommand)
            .UseDefaults()
            .UseHelp(ctx =>
            {
                ctx.HelpBuilder.CustomizeSymbol(foregroundColorOption,
                    firstColumnText: "--color <Black, White, Red, or Yellow>",
                    secondColumnText: "Specifies the foreground color. " +
                        "Choose a color that provides enough contrast " +
                        "with the background color. " +
                        "For example, a yellow foreground can't be read " +
                        "against a light mode background.");
                
                ctx.HelpBuilder.CustomizeLayout(
                _ =>
                    HelpBuilder.Default
                        .GetLayout()
                        .Skip(1) // Skip the default command description section.
                        .Prepend(
                            _ => AnsiConsole.Write(new FigletText(rootCommand.Description!))
                ));               
            })
            .Build();

        parser.Parse(args);
        
        return await rootCommand.InvokeAsync(args);
    }
}
```
```dotnet SampleCommandLineCustomHelp.dll -help``` and result:
```bat
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: --version
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.CommandLine.Parsing.StringExtensions.ValidTokens(Command command)
   at System.CommandLine.Parsing.StringExtensions.Tokenize(IReadOnlyList`1 args, CommandLineConfiguration configuration, Boolean inferRootCommand)
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   at System.CommandLine.CommandExtensions.GetDefaultInvocationPipeline(Command command, String[] args)
   at System.CommandLine.CommandExtensions.InvokeAsync(Command command, String[] args, IConsole console)
   at SampleCommandLineCustomHelp.Program.Main(String[] args) in C:\Users\tomi\source\GitHub\AWMySample\CommandLine\SampleCommandLineCustomHelp\Program.cs:line 69
   at SampleCommandLineCustomHelp.Program.<Main>(String[] args)
```

Is the documentation wrong or am I doing something wrong, maybe a bug?

Tamas

**Comment by tamasg** [comment]
I found it, I did it wrong. The beginning:
```csharp
using System.CommandLine.Parsing;
```
The end after the build:
```csharp
return await parser.InvokeAsync(args);
```
It works :smiley:, sorry for the unnecessary issue.
