### ISSUE TITLE
Parsing enum not working; throws System.ArgumentException

### ISSUE THREAD

**Issue by brandonh-msft** [dotnet/command-line-api#1819]
I have following enumeration defined:
```
public enum Platform
{
    Linux,
    Windows
}
```

And the following Option argument code:
```csharp
var platformOption = new Option<Platform>(new[] { "--platform", "-p" }, () => Platform.Linux, LocalizedStrings.BinaryAnalysisPlatformHelp)
{
    Arity = ArgumentArity.OneOrMore
};
AddOption(platformOption);
```

Yet when running the app with param `-p windows`, I get:
```
System.ArgumentException
  HResult=0x80070057
  Message=Type Microsoft.DotNet.UpgradeAssistant.Platform cannot be created without a custom binder.
  Source=System.CommandLine
  StackTrace:
   at System.CommandLine.Binding.ArgumentConverter.CreateEnumerable(Type type, Type itemType, Int32 capacity)
   at System.CommandLine.Binding.ArgumentConverter.ConvertTokens(Argument argument, Type type, IReadOnlyList`1 tokens, LocalizationResources localizationResources, ArgumentResult argumentResult)
   at System.CommandLine.Binding.ArgumentConverter.TryConvertArgument(ArgumentResult argumentResult, Object& value)
   at System.CommandLine.Parsing.ArgumentResult.Convert(Argument argument)
   at System.CommandLine.Parsing.ArgumentResult.GetArgumentConversionResult()
   at System.CommandLine.Parsing.ParseResultVisitor.ValidateAndConvertArgumentResult(ArgumentResult argumentResult)
   at System.CommandLine.Parsing.ParseResultVisitor.ValidateAndConvertOptionResult(OptionResult optionResult)
   at System.CommandLine.Parsing.ParseResultVisitor.Stop()
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   at System.CommandLine.Parsing.ParserExtensions.<InvokeAsync>d__3.MoveNext()
   at Microsoft.DotNet.UpgradeAssistant.Cli.Program.<Main>(String[] args)
```

Despite [our docs saying enums are supported](https://docs.microsoft.com/en-us/dotnet/standard/commandline/model-binding#enums).

**Comment by baronfel** [comment]
I'm pretty sure this is because of the mistmatched Arity in your sample - ArgumentArity.OneOrMore implies that you want an `Option<Platform[]>` instead. If you remove that explicit arity your sample will work.

**Comment by brandonh-msft** [comment]
> I'm pretty sure this is because of the mismatched Arity in your sample - ArgumentArity.OneOrMore implies that you want an `Option<Platform[]>` instead. If you remove that explicit arity your sample will work.

Thanks @baronfel I'll give this a shot,

Additionally, though, I have this:

```csharp
AddArgument(new Argument<FileSystemInfo[]>("files-or-directories", LocalizedStrings.BinaryAnalysisContentHelp)
{
    Arity = ArgumentArity.OneOrMore,
}.ExistingOnly());
```

which worked fine prior to updating to `preview4` of this lib but now am getting

```
Unhandled exception: System.ArgumentException: Type System.Collections.Generic.IReadOnlyCollection`1[System.IO.FileSystemInfo] cannot be created without a custom binder.
   at System.CommandLine.Binding.ArgumentConverter.CreateEnumerable(Type type, Type itemType, Int32 capacity)
```

**Comment by brandonh-msft** [comment]
@baronfel, changing my Arity did get me past the enum parsing problem - thanks!

I'm going to repurpose this item for the break in the `FileSystemInfo[]` usage.

**Comment by baronfel** [comment]
I think the Arity thing is the cause of that as well - between your versions the default token parsing changed (on purpose) to where you can declare how a particular `Argument<T> when  T is some kind of collection' is parsed. I think all you should have to do for the filesystem example is again remove the arity and go forward. Arity is mostly about 'how many tokens are required to return one instance of this thing'.

**Comment by JanKrivanek** [comment]
As mentioned - related to https://github.com/dotnet/command-line-api/issues/1727
