### ISSUE TITLE
dotnet-suggest broken for multiple tools

### ISSUE THREAD

**Issue by Blackclaws** [dotnet/command-line-api#1850]
dotnet-suggest is broken for a lot of standard tools.

My current installed list (according to dotnet-suggest list):
```
dotnet-ef
dotnet ef
security-scan
dotnet-grpc-cli
dotnet grpc-cli
dotnet-suggest
dotnet suggest
dotnet-grpc
dotnet grpc
reportgenerator
```

For most of these, except dotnet-suggest and dotnet-grpc, there are any valid suggestions returned. Usually an exception happens.

It seems to me as if dotnet-suggest should catch any exceptions and all output from a tool and only report suggestions _if_ there are any.

Printing the output from the tool completely breaks autocompletion functions for the existing shell shims, at least on zsh.

In general I don't think _executing_ those tools to get completions is a good idea either. It seems that if a tool is not built using System.CommandLine it will inevitably try to make sense of the [suggest] command which doesn't exist.

Running ```dotnet-suggest get -e``` on those executables yields:

dotnet-ef
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.<>c.<Execute>b__12_0(String a)
   at System.Linq.Enumerable.TakeWhileIterator[TSource](IEnumerable`1 source, Func`2 predicate)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute(String[] _)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Index was outside the bounds of the array.
```

dotnet-grpc-cli
```
Error: Unknown command '[suggest:32767]'.

       [suggest:32767] 
       ^^^^^^^^^^^^^^^ No such command
```

security-scan
```
Unhandled exception. System.InvalidOperationException: Invalid solution file path: ''
   at Microsoft.CodeAnalysis.MSBuild.DiagnosticReporter.Report(DiagnosticReportingMode mode, String message, Func`2 createException)
   at Microsoft.CodeAnalysis.MSBuild.PathResolver.TryGetAbsoluteSolutionPath(String path, String baseDirectory, DiagnosticReportingMode reportingMode, String& absolutePath)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.LoadSolutionInfoAsync(String solutionFilePath, IProgress`1 progress, ILogger msbuildLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.OpenSolutionAsync(String solutionFilePath, ILogger msbuildLogger, IProgress`1 progress, CancellationToken cancellationToken)
   at SecurityCodeScan.Tool.Program.Main(String[] args) in D:\a\security-code-scan\security-code-scan\SecurityCodeScan.Tool\Program.cs:line 296
   at SecurityCodeScan.Tool.Program.<Main>(String[] args)
╔═╗┌─┐┌─┐┬ ┬┬─┐┬┌┬┐┬ ┬  ╔═╗┌─┐┌┬┐┌─┐  ╔═╗┌─┐┌─┐┌┐┌
╚═╗├┤ │  │ │├┬┘│ │ └┬┘  ║  │ │ ││├┤   ╚═╗│  ├─┤│││
╚═╝└─┘└─┘└─┘┴└─┴ ┴  ┴   ╚═╝└─┘─┴┘└─┘  ╚═╝└─┘┴ ┴┘└┘

.NET tool by Jaroslav Lobačevski v5.6.3


Loading solution ''%
```

reportgenerator
```
2022-09-13T12:34:50: Arguments
2022-09-13T12:34:50:  [suggest:32767]
2022-09-13T12:34:50:  
2022-09-13T12:34:50: No report files specified.
2022-09-13T12:34:50: No target directory specified.
```

**Comment by Blackclaws** [comment]
Related: #1777

Though this issue is more about the fact that if dotnet-suggest can't deal with an executable it shouldn't return anything.

**Comment by Blackclaws** [comment]
> If my command-line app has a custom completion delegate that throws an exception, I want to see the exception so that I can fix it.
> 

Sure, in this case adding a --debug flag could help with that.

> > Printing the output from the tool completely breaks autocompletion functions for the existing shell shims, at least on zsh.
> 
> I expect that suggestions should go to stdout and any exceptions should go to stderr, keeping them separate. Does it not work like that?

No, it doesn't. Because dotnet-suggest cannot distinguish exceptions in the tool from normal output from the tool. Exceptions within dotnet-suggest are sent to stderr. The tool error is printed to stdout. Which especially when used in the context of a completion handler for a shell is particularly weird.

**Comment by Blackclaws** [comment]
> If dotnet-suggest supported a --debug flag, how would I add that flag when I notice that suggestions don't work right? I suppose the easiest way would be to edit the shell function that runs dotnet-suggest.
> 

Just run ```dotnet-suggest get --debug -e EXECUTABLEPATH -- full-line``` the same as the completions do

> What prints the tool error to stdout? [CommandLineBuilderExtensions.UseExceptionHandler](https://github.com/dotnet/command-line-api/blob/2.0.0-beta4.22272.1/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs#L315) prints the exception to stderr, and [SuggestionStore.GetCompletions](https://github.com/dotnet/command-line-api/blob/2.0.0-beta4.22272.1/src/System.CommandLine.Suggest/SuggestionStore.cs#L35) does not redirect stderr of the child process… but do the foreground color changes in [ConsoleExtensions](https://github.com/dotnet/command-line-api/blob/2.0.0-beta4.22272.1/src/System.CommandLine/IO/ConsoleExtensions.cs) go to stdout anyway? The `Platform.IsConsoleRedirectionCheckSupported` checks there look strange.

I don't know, and it really shouldn't matter. I'm quite sure that those tools simply don't use System.CommandLine at all, hence why dotnet-suggest doesn't do anything useful with them in the first place. However it should ignore non System.CommandLine tools entirely and not _execute_ them.

**Comment by jonsequitur** [comment]
>No, it doesn't. Because dotnet-suggest cannot distinguish exceptions in the tool from normal output from the tool. Exceptions within dotnet-suggest are sent to stderr. The tool error is printed to stdout. Which especially when used in the context of a completion handler for a shell is particularly weird.

This looks like a bug. Exceptions should definitely not be printed to stdout.

**Comment by Blackclaws** [comment]
> > No, it doesn't. Because dotnet-suggest cannot distinguish exceptions in the tool from normal output from the tool. Exceptions within dotnet-suggest are sent to stderr. The tool error is printed to stdout. Which especially when used in the context of a completion handler for a shell is particularly weird.
> 
> This looks like a bug. Exceptions should definitely not be printed to stdout.

It seems that this is more widespread than one might think though. In general though, _any_ output from the tool that is to be autocompleted should be supressed for ```dotnet-suggest get```

**Comment by jonsequitur** [comment]
Some of these tools might be using a version of `System.CommandLine` that isn't compatible with the version of `dotnet-suggest` that's in use. Support for cursor positioning (i.e. (`[suggest:32767]`) wasn't available in early versions. And of course  32767 is a very suspicious-looking cursor position. 

In the case of `dotnet-ef`, it doesn't appear to support completions at all, as `dotnet-ef [suggest]` results in an error (at least on version 6.0.8).

Better debugging support here would be useful. It should probably include some of the diagnostic approaches mentioned in https://github.com/dotnet/command-line-api/issues/1085#issuecomment-730583120 and #1648.

Related: #1771.

**Comment by Blackclaws** [comment]
> Some of these tools might be using a version of `System.CommandLine` that isn't compatible with the version of `dotnet-suggest` that's in use. Support for cursor positioning (i.e. (`[suggest:32767]`) wasn't available in early versions. And of course 32767 is a very suspicious-looking cursor position.
> 
> In the case of `dotnet-ef`, it doesn't appear to support completions at all, as `dotnet-ef [suggest]` results in an error (at least on version 6.0.8).
> 

dotnet-ef isn't written using System.CommandLine at all. Hence its even stranger that dotnet-suggest even picks it up as a supported completion target.

**Comment by Blackclaws** [comment]
As far as I can tell it registered all already installed tools when I installed it.

**Comment by drewburlingame** [comment]
> Yeah, I'm curious about how it got registered.

Aren't all global tools considered registered by default, thanks to GlobalToolsSuggestionRegistration?
