### ISSUE TITLE
[Bug] Type System.String cannot be created without a custom binder.

### ISSUE THREAD

**Issue by rfuzzo** [dotnet/command-line-api#1872]
Hello, 
on version `2.0.0-beta4.22272.1` I'm getting a consistent `System.ArgumentException:` exception.
Please find a minimal working example below:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.CommandLine.Hosting" Version="0.4.0-alpha.22272.1" />
		<PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
	</ItemGroup>

</Project>
```

```cs
using System.CommandLine;
using System.CommandLine.Builder;
using System.CommandLine.NamingConventionBinder;
using System.CommandLine.Parsing;

RootCommand rootCommand = new()
{
    new TestCommand(),
};

Parser parser = new CommandLineBuilder(rootCommand).UseDefaults().Build();
return parser.Invoke(args);

internal class TestCommand : Command
{
    public TestCommand() : base("test", "")
    {
        AddArgument(new Argument<FileSystemInfo[]>("path", "Input path."));

        AddOption(new Option<DirectoryInfo>(new[] { "--outpath", "-o" }, "Output path."));

        Handler = CommandHandler.Create<FileSystemInfo[], DirectoryInfo>(Action);
    }
    private int Action(FileSystemInfo[] path, DirectoryInfo outpath)
    {
        Console.WriteLine("testing");
        return 0;
    }
}
```
Exception:
```txt
Unhandled exception: System.ArgumentException: Type System.String cannot be created without a custom binder.
   at System.CommandLine.Binding.ArgumentConverter.CreateEnumerable(Type type, Type itemType, Int32 capacity)
   at System.CommandLine.Binding.ArgumentConverter.ConvertTokens(Argument argument, Type type, IReadOnlyList`1 tokens, LocalizationResources localizationResources, ArgumentResult argumentResult)
   at System.CommandLine.Binding.ArgumentConverter.ConvertObject(Argument argument, Type type, Object value, LocalizationResources localizationResources)
   at System.CommandLine.Binding.BindingContext.TryBindToScalarValue(IValueDescriptor valueDescriptor, IValueSource valueSource, LocalizationResources localizationResources, Nullable`1& boundValue)
   at System.CommandLine.NamingConventionBinder.ModelBinder.GetBoundValue(IValueSource valueSource, BindingContext bindingContext, IValueDescriptor valueDescriptor, Boolean includeMissingValues, Type parentType)
   at System.CommandLine.NamingConventionBinder.ModelBinder.GetBoundValues(IDictionary`2 bindingSources, BindingContext bindingContext, IReadOnlyList`1 valueDescriptors, Boolean enforceExplicitBinding, Type parentType, Boolean includeMissingValues)
   at System.CommandLine.NamingConventionBinder.ModelBinder.GetBestConstructorAndArgs(BindingContext bindingContext)
   at System.CommandLine.NamingConventionBinder.ModelBinder.CreateInstanceInternal(BindingContext bindingContext)
   at System.CommandLine.NamingConventionBinder.ModelBinder.GetBoundValue(IValueSource valueSource, BindingContext bindingContext, IValueDescriptor valueDescriptor, Boolean includeMissingValues, Type parentType)
   at System.CommandLine.NamingConventionBinder.ModelBinder.GetBoundValues(IDictionary`2 bindingSources, BindingContext bindingContext, IReadOnlyList`1 valueDescriptors, Boolean enforceExplicitBinding, Type parentType, Boolean includeMissingValues)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()```

**Comment by elgonzo** [comment]
I cannot reproduce. What args precisely are you passing?

Also, there is something quite strange with your project configuration. Your source code uses the `System.CommandLine.NamingConventionBinder` package. But your project file doesn't have a reference for this package.

So, how exactly is your project utilizing the `System.CommandLine.NamingConventionBinder` package? Is there perhaps a version mismatch between the System.CommandLine assembly and the System.CommandLine.NamingConventionBinder assembly your app is using?

**Comment by rfuzzo** [comment]
hmm I was passing `test aaa bbb`

**Comment by elgonzo** [comment]
Ah, the `-o` option is not in your args. If i try without the `-o` option, i can now also reproduce.

**Comment by dodexahedron** [comment]
This appears to be related to arity, and seems to be more of an issue with the exception being unclear than an actual bug with it.

The four cases for combinations of arity and whether the argument type is an array or not behave consistently as follows, in my testing:

| Arity > 1 | Type is an array | Result |
|--------|--------|--------|
| No | No | Works |
| No | Yes | Fails |
| Yes | No | Fails |
| Yes | Yes | Works |

The exception being thrown makes it seem like the library is at fault for not being able to handle some requested type. But the problem is the type and arity combination specified by the consumer. When they match, it works as expected.

I would propose that a better exception needs to be thrown to fix this.

**Comment by thomasrea0113** [comment]
The error is unclear, but the solution is to just provide a `CustomParser` to map the tokens to whatever target type is required if not an array.

```csharp
    private static readonly Argument<IReadOnlyList<string>> _commandOverrides = new("overrides")
    {
        Arity = ArgumentArity.ZeroOrMore,
        Description = AppText.CommandArgumentOverrides,
        CustomParser = r => r.Tokens.Select(t => t.Value).ToArray()
    };
```

But like @dodexahedron pointed out, this "just works" if you specify the argument type as `string[]`, though I would love to see `IReadOnlyList<string>`. work as well

**Comment by baronfel** [comment]
Instead of relying on the built in type dictionaries that S.CL contains, I've started making a series of custom parsers that can handle any T that is ISpanParsable - you can take a look at https://github.com/dotnet/sdk/blob/main/src/Cli/Microsoft.DotNet.Cli.CommandLine/SpanParsableExtensions.cs, maybe some of this will be useful to the broader community?

**Comment by dodexahedron** [comment]
> The error is unclear, but the solution is to just provide a `CustomParser` to map the tokens to whatever target type is required if not an array.
> 
>     private static readonly Argument<IReadOnlyList<string>> _commandOverrides = new("overrides")
>     {
>         Arity = ArgumentArity.ZeroOrMore,
>         Description = AppText.CommandArgumentOverrides,
>         CustomParser = r => r.Tokens.Select(t => t.Value).ToArray()
>     };
> But like [@dodexahedron](https://github.com/dodexahedron) pointed out, this "just works" if you specify the argument type as `string[]`, though I would love to see `IReadOnlyList<string>`. work as well

And, to be clear...

For built-in types, like System.String, this is unnecessary. You only need to make a parser if it's a type not already understood by the library, which *should* be relatively uncommon, in theory, since it is text input from the command line.

As long as the types and their arities match, you'll have no problem.

But the error makes it seem like a type is not supported when, in fact, it is. 🤷‍♂️
