### ISSUE TITLE
System.CommandLine doesn't work with Wasm

### ISSUE THREAD

**Issue by richlander** [dotnet/command-line-api#2195]
I tried using System.CommandLine with the `wasiconsole` app type/template

I get this:

```bash
Unhandled Exception:
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.IsOutputRedirectedCore()
   at System.Console.<get_IsOutputRedirected>g__EnsureInitialized|36_0()
   at System.Console.get_IsOutputRedirected()
   at System.CommandLine.IO.SystemConsole.get_IsOutputRedirected()
   at System.CommandLine.IO.SystemConsole.GetWindowWidth()
   at System.CommandLine.CommandLineConfiguration.DefaultHelpBuilderFactory(BindingContext context, Nullable`1 requestedMaxWidth)
   at System.CommandLine.Builder.CommandLineBuilder.<GetHelpBuilderFactory>g__CreateHelpBuilder|26_0(BindingContext bindingContext)
   at System.CommandLine.Invocation.ServiceProvider.<>c__DisplayClass1_0.<.ctor>b__3(IServiceProvider _)
   at System.CommandLine.Invocation.ServiceProvider.GetService(Type serviceType)
   at System.CommandLine.Binding.BindingContext.get_HelpBuilder()
   at System.CommandLine.Help.HelpResult.Apply(InvocationContext context)
   at System.CommandLine.Invocation.ParseErrorResult.Apply(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.GetExitCode(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<Invoke>g__FullInvocationChain|3_0(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(IConsole console)
   at System.CommandLine.CommandExtensions.Invoke(Command command, String[] args, IConsole console)
   at Program.<Main>$(String[] args)
```

**Comment by richlander** [comment]
This doesn't seem to be a generic issue: https://docs.wasmer.io/integrations/js/wasi/browser/examples/handling-io

This repo is likely the wrong one since it's not likely a SCL issue.

**Comment by richlander** [comment]
It's possible we won't fix this. Is it possible for SCL to do a runtime check on the OS and not check for redirected output?

**Comment by richlander** [comment]
@pavelsavara

**Comment by adamsitnik** [comment]
Fixed by https://github.com/dotnet/runtime/pull/87278, thank you all for your feedback and help!
