### ISSUE TITLE
UseHost() - can't have subcommand "config"

### ISSUE THREAD

**Issue by seanadams9** [dotnet/command-line-api#2220]
When using UseHost() the hosting action sets up a CliDirective with the name "config". If you have a subcommand with the same name "config" parsing fails with:

An item with the same key has already been added. Key: config
System.ArgumentException: An item with the same key has already been added. Key: config
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.CommandLine.Parsing.StringExtensions.<ValidTokens>g__AddCommandTokens|8_0(Dictionary`2 tokens, CliCommand cmd)
   at System.CommandLine.Parsing.StringExtensions.ValidTokens(CliCommand command, IReadOnlyList`1 directives)
   at System.CommandLine.Parsing.StringExtensions.Tokenize(IReadOnlyList`1 args, CliConfiguration configuration, Boolean inferRootCommand, List`1& tokens, List`1& errors)
   at System.CommandLine.Parsing.CliParser.Parse(CliCommand command, IReadOnlyList`1 arguments, String rawInput, CliConfiguration configuration)
   at System.CommandLine.Parsing.CliParser.Parse(CliCommand command, IReadOnlyList`1 args, CliConfiguration configuration)
   at System.CommandLine.CliConfiguration.Parse(IReadOnlyList`1 args)

**Comment by jonsequitur** [comment]
This bug is more general and affects any directive where the name collides with a command defined on the root.
