### ISSUE TITLE
Having a sub-command with a name that matches its parent crashes the parser

### ISSUE THREAD

**Issue by calebkiage** [dotnet/command-line-api#2260]
```csharp
using System.CommandLine;

var rootCommand = new RootCommand();
var cmd = new Command("test");
var cmd2 = new Command("test");

cmd.AddCommand(cmd2);
rootCommand.AddCommand(cmd);

return await rootCommand.InvokeAsync(args);
```

When trying to build the command structure above, the parser throws the below exception:

```
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: test
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.CommandLine.Parsing.StringExtensions.ValidTokens(Command command)
   at System.CommandLine.Parsing.StringExtensions.Tokenize(IReadOnlyList`1 args, CommandLineConfiguration configuration, Boolean inferRootCommand)
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   at System.CommandLine.CommandExtensions.GetDefaultInvocationPipeline(Command command, String[] args)
   at System.CommandLine.CommandExtensions.InvokeAsync(Command command, String[] args, IConsole console)
   at Program.<Main>$(String[] args) in ...
```

**Comment by jeffhandley** [comment]
We verified that we do have a class of name collision challenges here, regardless of symbol type, where we throw during parse. We are not going to fix them for now, as our position is such name collisions should be avoided in the symbol tree for sake of end-user usability. However, if there are enough concrete scenarios that emerge over time for this, we will consider updating the behavior to allow the collisions. Relaxing the behavior is easier to accomplish than constraining it later.
