### ISSUE TITLE
Unhelpful exception from AutoGeneratedProgram

### ISSUE THREAD

**Issue by dashesy** [dotnet/command-line-api#599]
When I try to use `DragonFly` I get this exception

```

$ ./TesterApp.exe -h

Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_WindowWidth()
   at System.CommandLine.HelpBuilder..ctor(IConsole console, Nullable`1 columnGutter, Nullable`1 indentationSize, Nullable`1 maxWidth)
   at System.CommandLine.CommandLineConfiguration.<>c.<get_HelpBuilderFactory>b__22_0(BindingContext context)
   at System.CommandLine.Invocation.ServiceProvider.GetService(Type serviceType)
   at System.CommandLine.Binding.BindingContext.get_HelpBuilder()
   at System.CommandLine.Invocation.HelpResult.Apply(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<InvokeAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<InvokeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.DragonFruit.CommandLine.<InvokeMethodAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.DragonFruit.CommandLine.<ExecuteAssemblyAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AutoGeneratedProgram.<Main>d__0.MoveNext() in D:\development\ComputerVision-ImageUnderstanding\TesterApp\obj\x64\Debug\net472\TesterApp.Program.g.cs:line 10
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AutoGeneratedProgram.<Main>(String[] args)

```

**Comment by dashesy** [comment]
Ok I use `git-bash` for most of my debugging. I had to use `winpty`

```bash
winpty ./TesterApp.exe -h
```

I wonder why it is needed now, when I used `Microsoft.Extensions.CommandLineUtils` and `app.Execute(args)` the console was fine, but now I need pty.

**Comment by flcdrg** [comment]
Seeing the same error trying to run an application as a Windows Service
