### ISSUE TITLE
System.CommandLine.DragonFruit how to add alias commands

### ISSUE THREAD

**Issue by dashesy** [dotnet/command-line-api#600]
`DragonFruit` is very nice, but it will not be very useful unless there is a way to customize command names, and add aliases.
Also, there seem to be many exceptions that are hard to understand:

```
Unhandled exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<TakeWhileIterator>d__27`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at System.CommandLine.Invocation.TypoCorrection.ProvideSuggestions(ParseResult result, IConsole console)
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass8_0.<<UseTypoCorrections>b__0>d.MoveNext()
```

**Comment by jonsequitur** [comment]
Can you provide sample code to reproduce this exception?

There's been some discussion around how to add aliases and subcommands to DragonFruit. See #128 and #525.

**Comment by dashesy** [comment]
The exception is [here](https://github.com/dotnet/command-line-api/issues/603) thanks that alias PR will be useful so I close this issue.
When there is an exception, it is not very clear right now exactly what is wrong.
