### ISSUE TITLE
"Unhandled exception: System.InvalidOperationException: Sequence contains no elements"

### ISSUE THREAD

**Issue by dashesy** [dotnet/command-line-api#603]
When I try to add an argument (instead of option) to the root handler I get this exception:

```C#
var detectorArg = new Argument("Detector");
// ...
rootCommand.AddArgument(detectorArg);
```

> Unhandled exception: System.InvalidOperationException: Sequence contains no elements

```

Unhandled exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<TakeWhileIterator>d__27`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at System.CommandLine.Invocation.TypoCorrection.ProvideSuggestions(ParseResult result, IConsole console)
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass8_0.<<UseTypoCorrections>b__0>d.MoveNext()

```

**Comment by Icontech** [comment]
This seems to be the same bug as previously mentioned in #578 .
