### ISSUE TITLE
Exception stack-traces when using System.CommandLine.DragonFruit are not friendly...

### ISSUE THREAD

**Issue by damageboy** [dotnet/command-line-api#668]
Here's a sample assertion from a program I have using System.CommandLine.DragonFruit:

Note:
1. I tried to catch the exception and Just print nothing instead of this wall of text (below):
     ```csharp
        public static unsafe void Main(...)
        {
            try {
                WrappedMain(...);
            }
            catch {
                Console.WriteLine("XXX");
            }
        }
    ```
    This does not work, I didn't bother to investigate why that is the case
2. Instead, the default behaviour here generated 90 lines of exception stack trace,
**84** (!) of which are internal stuff inside System.CommandLine.DragonFruit which I would claim that no normal user should care about? Wouldn't it make sense to never have this printed under any circumstances to the user, except for maybe debug builds of your own package?
```bash
Process terminated. Assertion failed.
depth=0 boundary=30, idx = 0 *t(24) <= pivot=12
   at QuickSortAvaganza.AVX2.Happy.AVX2DoublePumpedAlignedOverlapUnrolledWithPCSort`1.QuickSortInt32.VerifyBoundaryIsCorrect(Int32* left, Int32* right, Int32 pivot, Int32* boundary) in /home/dmg/projects/public/QuicksortAvaganza/QuickSortAvaganza/AVX2/Happy/07_AVX2DoublePumpedUnrolledWithPCSort.cs:line 809
   at QuickSortAvaganza.AVX2.Happy.AVX2DoublePumpedAlignedOverlapUnrolledWithPCSort`1.QuickSortInt32.VectorizedPartitionInPlace(Int32* left, Int32* right, Int64 hint) in /home/dmg/projects/public/QuicksortAvaganza/QuickSortAvaganza/AVX2/Happy/07_AVX2DoublePumpedUnrolledWithPCSort.cs:line 491
   at QuickSortAvaganza.AVX2.Happy.AVX2DoublePumpedAlignedOverlapUnrolledWithPCSort`1.QuickSortInt32.QuickSort(Int32* left, Int32* right, Int64 hint) in /home/dmg/projects/public/QuicksortAvaganza/QuickSortAvaganza/AVX2/Happy/07_AVX2DoublePumpedUnrolledWithPCSort.cs:line 208
   at QuickSortAvaganza.AVX2.Happy.AVX2DoublePumpedAlignedOverlapUnrolledWithPCSort`1.QuickSort(T[] array) in /home/dmg/projects/public/QuicksortAvaganza/QuickSortAvaganza/AVX2/Happy/07_AVX2DoublePumpedUnrolledWithPCSort.cs:line 27
   at Example.Program.WrappedMain(String typeList, String sizeList, Int32 maxLoops, Int32 modulo, Int32 forceValue, Double forceRate, Boolean noCheck, String statsFile) in /home/dmg/projects/public/QuicksortAvaganza/Example/Program.cs:line 93
   at Example.Program.Main(String typeList, String sizeList, Int32 maxLoops, Int32 modulo, Int32 forceValue, Double forceRate, Boolean noCheck, String statsFile) in /home/dmg/projects/public/QuicksortAvaganza/Example/Program.cs:line 49
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<BuildInvocationChain>b__0(InvocationContext invocationContext, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass1_0.<<ConfigureConsole>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass1_0.<ConfigureConsole>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseErrorReporting>b__22_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<UseParseErrorReporting>b__22_0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass8_0.<<UseTypoCorrections>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass8_0.<UseTypoCorrections>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<UseSuggestDirective>b__7_0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<UseParseDirective>b__6_0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__20_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<UseHelp>b__20_0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass3_0.<<UseVersionOption>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass3_0.<UseVersionOption>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__23_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<RegisterWithDotnetSuggest>b__23_0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass5_0.<<UseExceptionHandler>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass5_0.<UseExceptionHandler>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseDebugDirective>b__4_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<UseDebugDirective>b__4_0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<CancelOnProcessTermination>b__0_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<CancelOnProcessTermination>b__0_0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(IConsole console)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(IConsole console)
   at System.CommandLine.Invocation.InvocationExtensions.InvokeAsync(Parser parser, ParseResult parseResult, IConsole console)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationExtensions.InvokeAsync(Parser parser, ParseResult parseResult, IConsole console)
   at System.CommandLine.Invocation.InvocationExtensions.InvokeAsync(Parser parser, String[] args, IConsole console)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationExtensions.InvokeAsync(Parser parser, String[] args, IConsole console)
   at System.CommandLine.DragonFruit.CommandLine.InvokeMethodAsync(String[] args, MethodInfo method, String xmlDocsFilePath, Object target, IConsole console)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.DragonFruit.CommandLine.InvokeMethodAsync(String[] args, MethodInfo method, String xmlDocsFilePath, Object target, IConsole console)
   at System.CommandLine.DragonFruit.CommandLine.ExecuteAssemblyAsync(Assembly entryAssembly, String[] args, String entryPointFullTypeName, String xmlDocsFilePath, IConsole console)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.DragonFruit.CommandLine.ExecuteAssemblyAsync(Assembly entryAssembly, String[] args, String entryPointFullTypeName, String xmlDocsFilePath, IConsole console)
   at AutoGeneratedProgram.Main(String[] args) in /home/dmg/projects/public/QuicksortAvaganza/Example/obj/Debug/netcoreapp3.0/Example.Program.g.cs:line 10
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at AutoGeneratedProgram.Main(String[] args)
   at AutoGeneratedProgram.<Main>(String[] args)
```

**Comment by jonsequitur** [comment]
What do you think would be a more useful output? If a user encounters this error, by what process would you expect them to submit a bug report?

**Comment by ThiagoT1** [comment]
Actually, CommandHandler.Create accepts only ```Action``` or ```Func<int>``` handlers.

Is there a way to just return a useful string message to the user when a captured command goes wrong?

One might think a ```e.Message``` would be usefull, as we could ```throw new Exception("This is wrong")``` without the ```e.ToString()``` being displayed on the command window?

**Comment by jonsequitur** [comment]
> Is there a way to just return a useful string message to the user when a captured command goes wrong?

I'd ask two clarifying questions: 

* _Useful_ to the developer or the user? For example, is the error message intended to unblock the user, or is it only useful if the user passes it along to the developer in a bug report?
* _Goes wrong_ because the developer made a mistake or the user made a mistake? Did the developer create a bug or did the user enter invalid input?

I'll explain a bit of the thinking behind the current design, which tries to treat these two people's experiences separately. The short version is: exceptions are for developers.

Unhandled exceptions, thrown from framework or library code, are usually intended for developers and not users. In these cases the result of showing just the exception message will be something like `The given key was not present in the dictionary.` This lacks the context (i.e. a stack trace) to be useful to the developer, while still not giving enough information to the user to solve the problem.

If you want to provide a useful message to the user, the simplest approach is to write it to the console, which is what System.CommandLine's validation functionality will do.

**Comment by ThiagoT1** [comment]
Your reply was very helpful. Thank you!

Maybe then we should consider making it easier do write to console in different colors and indentations?

Maybe some sort of CLI mark down(ish) support?

The reason for this is that my first comment was all about an easy way to write RED text to the user lol.
