### ISSUE TITLE
./prog help <cmd> is throwing

### ISSUE THREAD

**Issue by ibigbug** [dotnet/command-line-api#677]
Stack:
```
PS C:\Users\i> powersession.exe help rec
Unhandled exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at System.CommandLine.Invocation.TypoCorrection.<>c__DisplayClass3_0.<GetPossibleTokens>b__1(ISymbol symbol)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.TakeWhileIterator[TSource](IEnumerable`1 source, Func`2 predicate)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at System.CommandLine.Invocation.TypoCorrection.ProvideSuggestions(ParseResult result, IConsole console)
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass8_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass3_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__23_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass5_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

My setup: https://github.com/ibigbug/PowerSession/blob/7bb17e6fce1257abffebcd61de04de08f2d5e3c3/PowerSession.Cli/Program.cs#L72

Not sure which line is causing the issue, haven't figure out how to do a minimal repro yet.

Can you please help to have a look?

**Comment by jonsequitur** [comment]
I updated to System.CommandLine.Experimental version 0.3.0-alpha.19528.1 and no longer got this error.

You can grab the latest versions from this feed:

https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json.
