### ISSUE TITLE
CommandLineBuilder.ConfigureConsole does not appear to behave as expected

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/command-line-api#701]
I have a couple of unit tests which validate the command-line parsing of my console app. I'm trying to have these tests uses a test console (inspired by `TestConsole`,  and also wraps around  `ITestOutputHelper`).

To do this, I call `CommandLineBuilder.ConfigureConsole`. However, this method does not appear to be have as expected.

For example, I have one unit tests which fails (on Windows) like this:

```
at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
at System.ConsolePal.get_WindowWidth()
at System.Console.get_WindowWidth()
at System.CommandLine.HelpBuilder..ctor(IConsole console, Nullable`1 columnGutter, Nullable`1 indentationSize, Nullable`1 maxWidth) in /_/src/System.CommandLine/Help/HelpBuilder.cs:line 47
at System.CommandLine.CommandLineConfiguration.<>c.<get_HelpBuilderFactory>b__22_0(BindingContext context) in /_/src/System.CommandLine/CommandLineConfiguration.cs:line 115
at System.CommandLine.Invocation.ServiceProvider.<.ctor>b__2_3() in /_/src/System.CommandLine/Invocation/ServiceProvider.cs:line 25
at System.CommandLine.Invocation.ServiceProvider.GetService(Type serviceType) in /_/src/System.CommandLine/Invocation/ServiceProvider.cs:line 43
at System.CommandLine.Binding.BindingContext.get_HelpBuilder() in /_/src/System.CommandLine/Binding/BindingContext.cs:line 27
at System.CommandLine.Invocation.ParseErrorResult.Apply(InvocationContext context) in /_/src/System.CommandLine/Invocation/ParseErrorResult.cs:line 20
at System.CommandLine.Invocation.InvocationPipeline.GetResultCode(InvocationContext context) in /_/src/System.CommandLine/Invocation/InvocationPipeline.cs:line 72
at System.CommandLine.Invocation.InvocationPipeline.Invoke(IConsole console) in /_/src/System.CommandLine/Invocation/InvocationPipeline.cs:line 38
at System.CommandLine.Invocation.InvocationExtensions.Invoke(Parser parser, ParseResult parseResult, IConsole console) in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 268
at System.CommandLine.Invocation.InvocationExtensions.Invoke(Parser parser, String[] args, IConsole console) in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 280
at [app].Main(String[] args, Func`3 runner, Func`4 recorder, Action`1 configureBuilder) in [app]\Program.cs:line 587
at [app].ProgramTests.NoArgumentsTest() in [app]\ProgramTests.cs:line 52
```

It appears `HelpBuilder` is getting its `IConsole` via DI, and `CommandLineBuilder.ConfigureConsole` does not override the console which is provided via DI?

Alternatively, it is not clear to me what happens when multiple `CommandLineBuilder.ConfigureConsole` is called multiple times. Does the last caller win? Do I get notified when there are competing implementations?

**Comment by jonsequitur** [comment]
I believe this is fixed.
