### ISSUE TITLE
Unhandled exception: System.ArgumentException: Arrays indexes must be set to an object instance.

### ISSUE THREAD

**Issue by dashesy** [dotnet/command-line-api#705]
Error:

```C#
Unhandled exception: System.ArgumentException: Arrays indexes must be set to an object instance.
Parameter name: parameters
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.CommandLine.Binding.ModelBinder.TryDefaultConstructorAndPropertiesStrategy(BindingContext context, Object& instance) in /_/src/System.CommandLine/Binding/ModelBinder.cs:line 151
   at System.CommandLine.Binding.ModelBinder.CreateInstance(BindingContext context) in /_/src/System.CommandLine/Binding/ModelBinder.cs:line 121
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context) in /_/src/System.CommandLine/Invocation/ModelBindingCommandHandler.cs:line 52
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationPipeline.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseErrorReporting>b__22_0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 367
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass8_0.<<UseTypoCorrections>b__0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 225
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 177
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__20_0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 335
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass4_0.<<UseVersionOption>b__0>d.MoveNext() in /_/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__23_0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 406
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass5_0.<<UseExceptionHandler>b__0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 142
```

The reason is the conversion that returns an array:

```C#
//...
                new Option(
                    new[] { "--imgs", "-i" },
                    "Path to an image or directory of supported images")
                {
                    Required = true,
                    Argument = new Argument<string[]>(TryConvertImagePathArray)
                    {
                        Arity = ArgumentArity.ExactlyOne
                    }
                },
//...
        private static bool TryConvertImagePathArray(SymbolResult result, out string[] value)
```

**Comment by dashesy** [comment]
I realized `string[]` will be fine if I add to to a [complex type](https://github.com/dotnet/command-line-api/blob/6bd45425505b81ad235f7c3192cf1ba97d79d5bf/samples/tutorial/BindingToCommandHandlers.md#more-complex-types). Since I have 7+ options for one of my commands, so I need to use complex type for it. 
I am going to use complex binding ( #651 ) for all the commands, as a workaround for this issue.

```C#
        class RootParams
        {
            public FileInfo Config { get; set; }
            public string[] Imgs { get; set; }
        }
```
