### ISSUE TITLE
ReflectionTypeLoadException when publishing console app

### ISSUE THREAD

**Issue by fleed** [dotnet/command-line-api#712]
Hi

I created an application that targets `netcoreapp3.0` and references the `Azure.Storage.Blobs` package, together with:

```xml
<PackageReference Include="System.CommandLine.DragonFruit" Version="0.3.0-alpha.19577.1" />
<PackageReference Include="System.CommandLine.Experimental" Version="0.3.0-alpha.19577.1" />
```

The application runs as expected with **F5** from Visual Studio, but if I publish it in release mode (`dotnet publish -c Release`) and then try to run it I get the following exception:

```
Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Azure.Core, Version=1.0.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.CommandLine.DragonFruit.EntryPointDiscoverer.FindStaticEntryMethod(Assembly assembly, String entryPointFullTypeName)
   at System.CommandLine.DragonFruit.CommandLine.ExecuteAssemblyAsync(Assembly entryAssembly, String[] args, String entryPointFullTypeName, String xmlDocsFilePath, IConsole console)
   at AutoGeneratedProgram.Main(String[] args) in
```

I can see that the package `Azure.Core 1.0.1` is referenced by `Azure.Storage.Blobs`. The assembly in the publish directory has the following *FullName*: `Azure.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8`

**Comment by KathleenDollard** [comment]
We think this is a point in time issue, so we are closing
