### ISSUE TITLE
Exception while getting Option's default value [getDefaultValue]

### ISSUE THREAD

**Issue by ENikS** [dotnet/command-line-api#847]
I am using layered configuration for an app with command argument being the very last 'override'. Something like this:
```c#
new Option<string>("--{owner}",
                  getDefaultValue: () => Configuration.GetSection("owner")?.Value ?? throw new Exception("owner information is missing"),
                  description: $"Repository {owner} or organization") { Required = true }
```
Basically, if no owner is provided I am attempting to get it from default config or graciously fail if none configured.

It would be infinitely more user friendly if the exception was handled in the framework and regular error message (with --help screen) displayed instead of .NET exception report.

**Comment by jonsequitur** [comment]
It's generally recommended to avoid using an exception for something that's not exceptional. We expect users to enter invalid input, so it's not really an exception case. 

You might try using `parseArgument` to consolidate the fallback and error messaging, something like this:

```csharp
var opt = new Option<string>("--{owner}",
        parseArgument: argResult =>
        {
            if (argResult.Tokens.Any())
            {
                // this is the user input, if any:
                return argResult.Tokens.Single().Value;
            }

            if (Configuration.GetSection("owner") is { } section)
            {
                // ...and here's the vaue from config, if any...
                return section.Value;
            }

            // ...and finally this error message will be shown to the user if no config value was found:
            argResult.ErrorMessage = "owner information is missing";
            return null;
        },
        isDefault: true, // This means the parseArgument delegate will be called even if the user didn't enter a value for this option.
        description: $"Repository owner or organization")
{ 
    Required = true
};
```

**Comment by ENikS** [comment]
I've tried it but unfortunately, `parseArgument` is not called when no argument is provided by the user. Kind of defeats the point of having the default mechanism.

As far as exceptional cases go, I have to disagree. There must be a way to inform framework that default is not created. Normally an exception should be designated to indicate acceptable error, as opposed to unexpected crush in user's code:
```c#
try
{
    getDefaultValue.Invoke();
}
catch (GetDefaultFailedException ex)
{
    // Report
    throw;
}

```

**Comment by ENikS** [comment]
Plus, think about errors being user friendly! This is hardly readable even by someone who knows what exception means:
```c#
Unhandled exception. System.ArgumentException: --owner is missing
   at changelog.Program.<>c.<Main>b__5_1() in P:\GitHub-Bot\Changelog\src\Program.cs:line 72
   at System.CommandLine.Argument`1.<>c__DisplayClass3_0.<.ctor>b__0()
   at System.CommandLine.Argument.<>c__DisplayClass28_0.<SetDefaultValueFactory>b__0(ArgumentResult _)
   at System.CommandLine.Argument.GetDefaultValue(ArgumentResult argumentResult)
   at System.CommandLine.Parsing.SymbolResult.<>c__DisplayClass28_0.<GetOrCreateDefaultArgumentResult>b__0(IArgument arg)
   at System.CommandLine.DictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 source, TKey key, Func`2 create)
   at System.CommandLine.Parsing.SymbolResult.GetOrCreateDefaultArgumentResult(Argument argument)
   at System.CommandLine.Parsing.ParseResultVisitor.PopulateDefaultValues()
   at System.CommandLine.Parsing.ParseResultVisitor.Stop(SyntaxNode node)
   at System.CommandLine.Parsing.SyntaxVisitor.Visit(SyntaxNode node)
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   at System.CommandLine.CommandExtensions.GetInvocationPipeline(Command command, String[] args)
   at System.CommandLine.CommandExtensions.Invoke(Command command, String[] args, IConsole console)
   at changelog.Program.Main(String[] args) in P:\GitHub-Bot\Changelog\src\Program.cs:line 91
```

Compared to:
```cmd
Option '--owner' is required.

get-pr-info:
  get-pr-info

Usage:
  get-pr-info [options]

Options:
  -dir, --path <path>               Relative path to the repository
  -o, --owner <owner> (REQUIRED)    Repository owner or organization
  -r, --repo <repo> (REQUIRED)      Repository name
  -as, --user <user> (REQUIRED)     Run as <User>
  --version                         Show version information
  -?, -h, --help                    Show help and usage information


```

**Comment by jonsequitur** [comment]
The parser, and the default value handler, are not only called during invocation, but also when getting tab completions and generating help. For this reason, System.CommandLine's design doesn't prefer exception handling for user feedback. But if your default value delegate can hit an exception, you might embed a catch block in the `parseArgument` delegate so it shares context with the error messaging. 

> I've tried it but unfortunately parseArgument is not called when no argument is provided by the user. Kind of defeats the point of having the default mechanism.

If `parseArgument` isn't getting called when `isDefault` is set to `true`, this sounds like a bug. Can you provide some code that repros the issue?

> Plus, think about errors being user friendly! This is hardly readable even by someone who knows what exception means:

To use exceptions for user-facing messages, or clean up the verbose exception output, you can customize the behavior using `CommandLineBuilder.UseExceptionHandler`.

Because you're using a custom exception type and your exception message contain user-actionable information, this approach would work well.

Other exception messages, though, will be just as cryptic to an average user as a stack trace. The stack trace is the default we chose because we assume an unhandled exception is a bug and only actionable by the developer, not the user. A straightforward way for the user to pass along bug information to the developer is to paste the stack trace.  We're open to a more useful default, so this is just to explain the thought process so far.

Related: #350, #668.

**Comment by ENikS** [comment]
The Exception is never thrown:
```c#
using System;
using System.CommandLine;
using System.CommandLine.Invocation;

namespace changelog
{
    class Program
    {
        static int Main(string[] args)
        {
            var cmd = new RootCommand("AppName")
            {
                new Option<string>(new [] {$"--Repository.Owner", $"-o" },
                                   //getDefaultValue: () => throw new ArgumentException($"--Repository.Owner is missing"),
                                   parseArgument: (a) => throw new ArgumentException($"--Repository.Owner is missing"),
                                   description: $"Repository Repository.Owner or organization"),
            };

            cmd.Handler = CommandHandler.Create<string>((owner) =>
            {
                Console.WriteLine($"Owner is: {owner}");
            });

            return cmd.Invoke(args);
        }

    }
}

```

**Comment by ENikS** [comment]
If I am trying to throw an exception it is not being handled by the handler:
```c#
static int Main(string[] args)
{
    var cmd = new RootCommand("Name")
    {
        new Option<string>(new string[] {$"--owner", "-o" },
                            //parseArgument: (a) => null,
                            getDefaultValue: () => throw new Exception("Test"),
                            description: $"Repository owner or organization"),
    };

    cmd.Handler = CommandHandler.Create<string>((owner) =>
    {
        Console.WriteLine($"option value: {owner}");
    });


    var builder = new CommandLineBuilder(cmd)
        .UseExceptionHandler((e, i) => Console.WriteLine($"Exception")) <-- never executed
        .UseDefaults()
        .Build();

    return builder.Invoke(args);
}
```

**Comment by ENikS** [comment]
If you could change few lines in [this method](https://github.com/dotnet/command-line-api/blob/25e6b36ab6ba05c00b60d7bbcee300c7adc00209/src/System.CommandLine/Parsing/ParseResultVisitor.cs#L312) to be like this, it would solve the problem:
```c#
private void PopulateDefaultValues()
{
    var commandResults = _innermostCommandResult
        .RecurseWhileNotNull(c => c.Parent as CommandResult);

    foreach (var commandResult in commandResults)
    {
        foreach (var symbol in commandResult.Command.Children)
        {
            var symbolResult = _rootCommandResult.FindResultFor(symbol);

            if (symbolResult == null)
            {
                try
                {
                    switch (symbol)
                    {
                        case Option option when option.Argument.HasDefaultValue:

                            var optionResult = new OptionResult(
                                option,
                                null,
                                commandResult);

                            var childArgumentResult = optionResult.GetOrCreateDefaultArgumentResult(
                                option.Argument);

                            optionResult.Children.Add(childArgumentResult);
                            commandResult.Children.Add(optionResult);
                            _rootCommandResult.AddToSymbolMap(optionResult);

                            break;

                        case Argument argument when argument.HasDefaultValue:

                            var argumentResult = commandResult.GetOrCreateDefaultArgumentResult(
                                argument);

                            commandResult.Children.Add(argumentResult);
                            _rootCommandResult.AddToSymbolMap(argumentResult);

                            break;
                    }
                }
                catch (GetDefaultFailedException)
                {
                }
            }

            if (symbolResult is OptionResult o &&
                o.Option.Argument.Type == typeof(bool) &&
                o.Children.Count == 0)
            {
                o.Children.Add(
                    new ArgumentResult(
                        o.Option.Argument,
                        o));
            }
        }
    }
}
```
Adding try/catch around default value creation method with custom exception should allow desired behavior

**Comment by jonsequitur** [comment]
I verified that with the following change, your `parseArgument` delegate will be called and the exception thrown:

```csharp
var cmd = new RootCommand("AppName")
{
    new Option<string>(new [] {$"--Repository.Owner", $"-o" },
                        //getDefaultValue: () => throw new ArgumentException($"--Repository.Owner is missing"),
                        parseArgument: (a) => throw new ArgumentException($"--Repository.Owner is missing"),
// ADDED THIS:
                        isDefault: true, 
// ----------
                        description: $"Repository Repository.Owner or organization"),
};

```

Any suggestions on making this clearer or more discoverable?

Regarding a PR, we wouldn't want to make a design change that encourages throwing an exception during parsing. Keep in mind that tab completions, help generation, and other tooling support would then need to handle this exception everywhere upstream. This is many more code paths than just the `PopulateDefaultValues` method.

For example, given such an approach, the following would throw, breaking tab completion, and the error message wouldn't reach the user anyway (or possibly some shells would have the user tab through lines of error output):

```csharp
var suggestions = cmd.GetSuggestions("--Re");
```

So every code path using the parsing APIs, even indirectly, would now have to handle these exceptions, which the compiler doesn't communicate well as part of a method's possible "return values".

**Comment by ENikS** [comment]
I've tried your suggestion, but exception handler is still being ignored:
```c#
        static int Main(string[] args)
        {
            var cmd = new RootCommand("Name")
            {
                new Option<string>(new string[] {$"--owner", "-o" },
                                  parseArgument: (a) => throw new ArgumentException("Test"),
                                  isDefault: true,
                                  description: $"Repository owner or organization") { Required = true },
            };

            cmd.Handler = CommandHandler.Create<string>((owner) =>
            {
                Console.WriteLine($"option value: {owner}");
            });


            var builder = new CommandLineBuilder(cmd)
                .UseExceptionHandler((e, i) => Console.WriteLine($"Exception")) <-- never executed
                .UseDefaults()
                .Build();

            return builder.Invoke(args);
        }
```

**Comment by ENikS** [comment]
I see your point and it makes sense. I've got it working now and it does exactly what I need. 
I wish documentation had more detailed explanation for the differences in these two and the design decisions behind the logic.

Thank you for your help.

**Comment by ENikS** [comment]
Playing with the library a bit more I'd like to compliment the team on excellent work. Very useful stuff!
