### ISSUE TITLE
Arithmetic overflow exception thrown during call for suggestions

### ISSUE THREAD

**Issue by michaelgwelch** [dotnet/command-line-api#997]
I'm still working on a minimal reproducible example:

```bash
$ enuf lookup attrUnhandled exception. System.AggregateException: One or more errors occurred. (Arithmetic operation resulted in an overflow.)
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at System.CommandLine.Parsing.SymbolResult.MaximumArgumentCapacity()
   at System.CommandLine.Parsing.SymbolResult.get_RemainingArgumentCapacity()
   at System.CommandLine.Parsing.SymbolResult.get_IsArgumentLimitReached()
   at System.CommandLine.Parsing.ParseResultExtensions.GetSuggestions(ParseResult parseResult, Nullable`1 position)
   at System.CommandLine.Invocation.SuggestDirectiveResult.Apply(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.GetResultCode(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(IConsole console)
   at System.CommandLine.CommandExtensions.InvokeAsync(Command command, String[] args, IConsole console)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Enuf.Program.Main(String[] args) in /Users/mgwelch/Documents/repos/enuf/enuf.cli/Program.cs:line 93
```

**Comment by michaelgwelch** [comment]
I said it shouldn't overflow, but I'm wrong. The [Sum](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.sum?view=netcore-3.1#System_Linq_Enumerable_Sum_System_Collections_Generic_IEnumerable_System_Int32__) method explicitly calls out the fact that it will throw on overflow.
